### ISSUE TITLE
[Bug] User with username defined in spec does not get dropped at reconciliation

### ISSUE THREAD

**Issue by Vidalee** [mariadb-operator/mariadb-operator#104]
**Describe the bug**

User with username defined in spec (spec.name) are not dropped at reconciliation or when the CRD is deleted.

**Expected behaviour**

**Steps to reproduce the bug**

**Additional context**

Seems like it is because the DropUser method of the controller use the CRD name even if `spec.name` is set.

**Environment details**:
- Kubernetes version:
- mariadb-operator version: 0.0.12
- Install method: helm, OLM or static manifests
- Install flavour: minimal, recommended or custom

**Comment by mmontes11** [comment]
Hey @Vidalee ! Great to see you again.

No worries at all, I didn't quite catch this case either, just replied to your PR, left a suggestion:
- https://github.com/mariadb-operator/mariadb-operator/pull/105#pullrequestreview-1419079837
