### ISSUE TITLE
[Bug] Status conditions changed in `v0.0.12` - argocd 

### ISSUE THREAD

**Issue by mmontes11** [mariadb-operator/mariadb-operator#106]
**Describe the bug**
Hey @Vidalee, this is just to make you aware that the Status conditions changed considerably in the release in the `v0.0.12`, and also that we introduced some new ones, see:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/controllers/mariadb_controller.go#L365-L381
- https://github.com/mariadb-operator/mariadb-operator/blob/main/api/v1alpha1/mariadb_types.go#L249-L259
- https://github.com/mariadb-operator/mariadb-operator/blob/main/api/v1alpha1/condition_types.go#L4-L8

So this probably conflicted with your changes in the [argo-cd](https://github.com/argoproj/argo-cd) project:
- https://github.com/argoproj/argo-cd/pull/13143

Sorry about that, we needed to refactor this status conditions to ensure that no race conditions happen during a primary switchover, see the [pkg/replication](https://github.com/mariadb-operator/mariadb-operator/tree/main/pkg/controller/replication) for more detail and a sample [resource](https://github.com/mariadb-operator/mariadb-operator/blob/main/config/samples/mariadb_v1alpha1_mariadb_replication.yaml) to configure this feature.

Don't feel pushed about to do this issue, just if you find the time! I will try to get into argo-cd as well! Feel free to get in touch in our new channels if you need more details about the status conditions:
- https://github.com/mariadb-operator/mariadb-operator#get-in-touch

**Expected behaviour**
Support new status conditions in `argo-cd` and check if the previous ones still work. The semantics in the old ones stays the same, it just changed the way we set them, so probably the current changes to know if the deployment is progressing are still valid.

**Comment by mmontes11** [comment]
> My only hardcoded values are for condition.status == "False" and condition.reason == "Failed", so as long as they do not change, along with their meaning, I should not be impacted.

Fair enough, thanks for the detailed explanation. I will respect this values in future releases. I think this will cover the majority of the cases and its best keeping it simple and generic.

I just seen one case that is not covered but it's not related to the latest changes, if the `StatefulSet` gets stucked  it would return `StatefulSetNotReady` reason:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/pkg/conditions/ready.go#L58
- https://github.com/mariadb-operator/mariadb-operator/blob/main/controllers/mariadb_controller.go#L378

in this case it would be seen as `Progressing` on the ArgoCD side. But there's no way to check if the Pods are really coming up i.e. progressing indeed or they are stucked, so anyway, not a big deal.

Other than that, the other status conditions do not have a "negative" reason that you could checck
- https://github.com/mariadb-operator/mariadb-operator/blob/main/api/v1alpha1/condition_types.go#L14-L16

So this is an issue on the `mariadb-operator` side. Let me know if you think we should cover this, otherwise I will close this issue. Thanks for the cooperation 🙇🏻

**Comment by Vidalee** [comment]
> I just seen one case that is not covered but it's not related to the latest changes, if the `StatefulSet` gets stucked it would return `StatefulSetNotReady` reason:

I suppose it can happen when the pods can't be ready, but since we can't reliably tell whether the `StatefulSet` is indefinitely stuck or not, and it's possible the state will resolve itself, we should be `Progressing`.
(As says the [ArgoCD doc](https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#:~:text=Progressing%20%2D%20the%20resource%20is%20not%20healthy%20yet%20but%20still%20making%20progress%20and%20might%20be%20healthy%20soon): "Progressing - the resource is not healthy yet but still making progress and *might* be healthy soon")

So let's leave it as it is 😃

**Comment by mmontes11** [comment]
@Vidalee that sounds reasonable! thank you so much for investigating this 🦭 ❤️ 

This will help with the `mariadb-operator` adoption in the Argo community! 🐙 

Closing!
