### ISSUE TITLE
[Bug] Update Helm post-install CLI message 

### ISSUE THREAD

**Issue by mariadb-pieterhumphrey** [mariadb-operator/mariadb-operator#1063]
embedded link post helm install is broken due to docs change.
Not sure where to go next? 
https://github.com/mariadb-operator/mariadb-operator#quickstart
should be: https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/quickstart.md

**Comment by mmontes11** [comment]
This can be updated here:
https://github.com/mariadb-operator/mariadb-operator/blob/3ff9648441ebfd0ba7f1054bc60f48d331731106/deploy/charts/mariadb-operator/templates/NOTES.txt#L4

Feel free to raise a PR
