### ISSUE TITLE
[Feature] Support Backup and Restore for Individual Logical Databases

### ISSUE THREAD

**Issue by philosapiens** [mariadb-operator/mariadb-operator#129]
The current backup and restore functionality in the MariaDB Operator is limited to all logical databases within a MariaDB instance. This request seeks to add support for selectively backing up and restoring individual logical databases.

**Proposed Changes:**

- Modify the backup mechanism to allow specifying one or more logical databases for backup.
- Enhance the restore process to enable restoring specific logical databases from a backup (e.g. making use of the `--one-database` flag).
- Update documentation to reflect the new backup and restore functionality.

**Benefits:**

- Granular backup and restore capabilities for specific logical databases.
- Improved resource utilization and reduced backup/restore times.
- Enhanced disaster recovery by swiftly recovering individual databases.

**Comment by ibotty** [comment]
Regarding the restore, I would propose to also have `databases` (plural), so that it's possible to restore two schemas together.  This is sometimes necessary for FKs that span multiple schemas.
