### ISSUE TITLE
[Feature] Cross-namespace `mariaDbRef` support

### ISSUE THREAD

**Issue by mmontes11** [mariadb-operator/mariadb-operator#136]
**Describe the solution you'd like**
Be able to refer to `MariaDB` instances in different namespaces allowing to have shared cross-namespace `MariaDB` instances. This implies changing our [MariaDBRef](https://github.com/mariadb-operator/mariadb-operator/blob/main/api/v1alpha1/base_types.go#L37) object to use a [ObjectReference](https://pkg.go.dev/k8s.io/api/core/v1#ObjectReference) instead of a [LocalObjectReference](https://pkg.go.dev/k8s.io/api/core/v1#LocalObjectReference) to be able to specify a `namespace`. 

**Describe alternatives you've considered**
Use a per-namespace `MariaDB` instance as we currently support.

**Additional context**
This feature may introduce security concerns:
- By default, tenants will be able to connect, create users, grants and even execue sql scripts in `MariaDB` instances living in different namespaces

This will need to be mitigated by:
- Locking down RBAC to restrict object permissions. For example:
   - Platform teams will be able to create `Backups` and `Restores` whereas an application aren't able to create such database admin resources.
   - Platform tenants are able to configure `Users`, `Grants` and `Databases` whereas application tenants are only able to configure `Connections` using the credentials configured by the platform tenants.
- Introduce a policy engine such as [Kyverno](https://kyverno.io/) to define policies on the `mariadb-operator` CRDs
- Create additional policy CRDs managed by `mariadb-operator` to restrict access across namespaces. cert-manager and the Gateway API have already solved this problem:
   - cert-manager's [CertificateRequestPolicy](https://cert-manager.io/docs/projects/approver-policy/)
   - Gateway API's [ReferenceGrant](https://gateway-api.sigs.k8s.io/api-types/referencegrant/)
   
The last 2 points will be implemented in further releases.

**Comment by outductor** [comment]
We need this for propagating user's password secret. Is there a good way?

**Comment by mmontes11** [comment]
@outductor could you provide more details? I'm guessing that you are willing to get the connection string to a MariaDB in a different namespace maybe? Something like:

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Connection
metadata:
  name: connection
  namespace: app
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
 ....
```
The aim of this feature is allowing  `spec.mariaDbRef` to provide cross-namespace references in all the CRDs: `Connection`, `Backup`, `Restore` ... etc 

If this is not what you want, please open a different issue and let's discuss it there 🙏🏻
