### ISSUE TITLE
[Feature] Add custom annotation to PVC

### ISSUE THREAD

**Issue by jbperrin88** [mariadb-operator/mariadb-operator#138]
**Is your feature request related to a problem? Please describe.**
I use ArgoCD to deploy mariadb via this operator.
When i delete my ArgoCD application , all ressources are delete (even PVC)
ArgoCD can avoid this behaviour with custom annotation :
https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#no-resource-deletion

**Describe the solution you'd like**
Add annotation to PVC ( maybe to mariaDB volumeClaimTemplate )

**Describe alternatives you've considered**
none 

**Additional context**
ArgoCD

**Environment details**:
Openshift on compact cluster with mariadb Operator Version 0.15.1

**Comment by mmontes11** [comment]
Hey @jbperrin88 ! 

Extra labels and annotations can be added to all children resources by specifying `spec.inheritMetadata` in the `MariaDB` CRD:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/mariadb_v1alpha1_mariadb_metadata.yaml#L7..L11

Can you give it a try?

**Comment by jbperrin88** [comment]
Nice !

I'll try but it may be too much for my need .

I'll like to only label PVC cause other ressources can be deleted by argocd .

Thanks for you answer !

**Comment by mmontes11** [comment]
Hey @jbperrin88 ! 

I see, in that case you can set the `metadata.labels` in the `MariaDB` `spec.volumeClaimTemplate` field, as you pointed out in the issue:
https://github.com/mariadb-operator/mariadb-operator/blob/3f5e6a35e9f3b74f437a42a1825674163412335c/examples/manifests/mariadb_v1alpha1_mariadb.yaml#L23

We using the same API as the regular `StatefulSet`  `spec.volumeClaimTemplate` field:
- https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#persistentvolumeclaim-v1-core

I believe this should cover your case, let me know how it goes

**Comment by jbperrin88** [comment]
I'll keep you update soon . Thanks a lot for your work and your time .

Appreciate it !

**Comment by mmontes11** [comment]
Fixed by:
- https://github.com/mariadb-operator/mariadb-operator/pull/185

**Comment by jbperrin88** [comment]
Nice 👍

I'll keep you update about this
