### ISSUE TITLE
[Bug] HA is broken with kube-dns

### ISSUE THREAD

**Issue by wasd171** [mariadb-operator/mariadb-operator#139]
**Describe the bug**

I have an issue when trying to use `mariadb-operator` in HA replication setup with `kube-dns`. The `mariadb` resource fails with the following event:

```
Error reconciling Replication: error reconciling 'reconcile Primary' phase: error getting new primary client: error getting new primary client: error creating replica '0' client: dial tcp: lookup career-lunch-cluster-mariadb-0.career-lunch-cluster-mariadb.default.svc.cluster.local on 10.104.0.10:53: no such host
```

[Documentation](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations) specifies that in order for FQDN of the `Pod` within a `StatefulSet` to be reachable, a [headless Service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) (with `clusterIP: None`) must be created. I can see that `mariadb-operator` creates a regular `Service` and `clusterIP` field gets populated automatically.

**Expected behaviour**
A headless service should be created for pods to be reachable.

**Steps to reproduce the bug**
Deploy a [MariaDB cluster with replication](https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/mariadb_v1alpha1_mariadb_replication.yaml) to a k8s cluster with `kube-dns`.

**Additional context**
This works with CoreDNS, probably they follow the specification more loosely.
I suppose that the change should be minor: https://github.com/mariadb-operator/mariadb-operator/blob/3f5e6a35e9f3b74f437a42a1825674163412335c/controllers/mariadb_controller.go#L259

^ This should also set `clusterIP: None`

I was able to create a copy of a `StatefulSet` + `Service` (with `clusterIP: None`) and everything started to work.

**Environment details**:
- Kubernetes version: `v1.26.3`
- mariadb-operator version: `0.15.1`
- Install method: helm
- Install flavour: recommended

**Comment by mmontes11** [comment]
Hey there! This has been addressed as part of the Galera support:
- https://github.com/mariadb-operator/mariadb-operator/pull/122

We are now creating an `*-internal` service with `clusterIP: None`:
https://github.com/mariadb-operator/mariadb-operator/blob/3f608b136680f0814d4b9b91801129dcfff81a28/controllers/mariadb_controller.go#L463

It will be released in `v0.0.16`! Stay tuned! 🚀
