### ISSUE TITLE
[Bug] Galera Cluster deployment ready state

### ISSUE THREAD

**Issue by dbrown-auto** [mariadb-operator/mariadb-operator#159]
The statefulset never becomes ready following a basic Galera deployment

The query going to http://mariadb-0.mariadb-internal.default.svc.kubernetes fails to respond. mariadb-0.mariadb-internal.default.svc.cluster.local works so should it be using that url?

> kubectl get mariadb -n default

mariadb   False   Error reconciling Galera: error disabling bootstrap in Pod 0: error doing request: Delete "http://mariadb-0.mariadb-internal.default.svc.kubernetes:5555/api/bootstrap": dial tcp: lookup mariadb-0.mariadb-internal.default.svc.kubernetes on 10.96.0.10:53: no such host   All           3m32s

Once the cluster comes up all nodes except for the primary node can be restarted and rejoin the cluster without issue. The primary node is trying to bootstrap again and will remain in a failed state. 

**Expected behaviour**

I would expect the statefulset to move to a ready state

NAME      READY   STATUS      PRIMARY POD   AGE
mariadb   True       Ready        All                      3m29s

**Steps to reproduce the bug**

Apply configuration above. 

**Additional context**
Due to the api failure the following is left on the primary node (mariadb-0) 
root@mariadb-0:/# cat /etc/mysql/mariadb.conf.d/1-bootstrap.cnf
[galera]
wsrep_new_cluster="ON"

removing this file allows mariadb-0 to restart without failure but doesn't obviously fix the issue and the statefulset remains in a Not ready state. 

**Environment details**:
- Kubernetes version: v1.27.3
- mariadb-operator version: 0.17.0
- Install method: OLM
- Install flavour: recommended

**Comment by dbrown-auto** [comment]
For some reason the code was excluded in the original post

`---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: default
spec:
  podSecurityContext:
    runAsUser: 0

  replicas: 3

  galera:
    enabled: true
    sst: rsync
    replicaThreads: 1
    agent:
      image:
        repository: ghcr.io/mariadb-operator/agent
        tag: "v0.0.2"
        pullPolicy: IfNotPresent
      port: 5555
      kubernetesAuth:
        enabled: true
        authDelegatorRoleName: mariadb-galera-auth
      gracefulShutdownTimeout: 5s
    recovery:
      enabled: true
      clusterHealthyTimeout: 1m
      clusterBootstrapTimeout: 5m
      podRecoveryTimeout: 3m
      podSyncTimeout: 3m
    initContainer:
      image:
        repository: ghcr.io/mariadb-operator/init
        tag: "v0.0.3"
        pullPolicy: IfNotPresent
    volumeClaimTemplate:
      resources:
        requests:
          storage: 50Mi
      accessModes:
        - ReadWriteOnce
  myCnf: |
    [mysqld]
    bind-address=0.0.0.0
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M
    init_connect='SET NAMES utf8mb4'

  updateStrategy:
    type: RollingUpdate
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: workload
            operator: In
            values:
            - core
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: workload
            operator: In
            values:
            - core
        topologyKey: "kubernetes.io/hostname"
  database: mariadb
  env:
    - name: TZ
      value: SYSTEM
  envFrom:
    - configMapRef:
        name: mariadb
  image:
    pullPolicy: IfNotPresent
    repository: mariadb
    tag: 10.7.4
  passwordSecretKeyRef:
    key: password
    name: mariadb
  port: 3306
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  rootPasswordSecretKeyRef:
    key: root-password
    name: mariadb
  username: mariadb
  volumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
`

**Comment by mmontes11** [comment]
Hey there @dbrown-auto ! Thanks for bringing this up

> The query going to http://mariadb-0.mariadb-internal.default.svc.kubernetes/ fails to respond. mariadb-0.mariadb-internal.default.svc.cluster.local works so should it be using that url?

It depends, is `cluster.local` the DNS name of your cluster? If not, this won't work, but you can tweak it by setting the `clusterName` value in the helm chart:

https://github.com/mariadb-operator/mariadb-operator/blob/8295963114e8305daeeab98e9472ccd8164b63aa/deploy/charts/mariadb-operator/values.yaml#L15

> mariadb False Error reconciling Galera: error disabling bootstrap in Pod 0: error doing request: Delete "http://mariadb-0.mariadb-internal.default.svc.kubernetes:5555/api/bootstrap": dial tcp: lookup mariadb-0.mariadb-internal.default.svc.kubernetes on 10.96.0.10:53: no such host All 3m32s

This is the operator performing a DELETE request to the agent in order to delete the bootstrap config that you pointed out: `/etc/mysql/mariadb.conf.d/1-bootstrap.cnf`. It's a DNS resolution problem, maybe it has to do with your cluster name? can you try running this from inside the cluster?:

```bash
nslookup /mariadb-0.mariadb-internal.default.svc.kubernetes
```

And also provide the output of the following command?:

```bash
kubectl get endpoints mariadb-galera-internal -n default -o yaml
```

**Comment by dbrown-auto** [comment]
Hi Martin

Thanks for the quick reply. 

I checked the 'cluserName:' and looks like I has messed it up somehow

This fails which I expected. 
'nslookup mariadb-0.mariadb-internal.default.svc.kubernetes'

> kubectl get endpoints mariadb-internal -n default -o yaml
```
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-07-18T01:50:03Z"
  creationTimestamp: "2023-07-18T01:50:00Z"
  labels:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadb
    service.kubernetes.io/headless: ""
  name: mariadb-internal
  namespace: dcb
  resourceVersion: "4177742"
  uid: 10ffe351-8f1d-47ed-a276-3eaa8d967189
subsets:
- addresses:
  - hostname: mariadb-1
    ip: 10.255.140.181
    nodeName: cbdc-k8wo-001
    targetRef:
      kind: Pod
      name: mariadb-1
      namespace: dcb
      uid: a399eb2f-a23f-4dfb-be08-e9729a0c20aa
  - hostname: mariadb-2
    ip: 10.255.20.156
    nodeName: dpdc-k8wo-001
    targetRef:
      kind: Pod
      name: mariadb-2
      namespace: dcb
      uid: 4eaf3036-36c0-4a99-8973-84863c9f3894
  - hostname: mariadb-0
    ip: 10.255.214.164
    nodeName: tdc3-k8wo-001
    targetRef:
      kind: Pod
      name: mariadb-0
      namespace: dcb
      uid: 21a8a73f-67da-4b77-bffa-9a7839d23787
  ports:
  - name: sst
    port: 4568
    protocol: TCP
  - name: ist
    port: 4567
    protocol: TCP
  - name: mariadb
    port: 3306
    protocol: TCP
  - name: agent
    port: 5555
    protocol: TCP
  - name: cluster
    port: 4444
    protocol: TCP
```

Thank you again we are almost there. 
Error reconciling Galera: error disabling bootstrap in Pod 0: unauthorized
Zero troubleshooting on this yet so will come back if I run I can't figure it out. 

Kind regards

**Comment by mmontes11** [comment]
Hey @dbrown-auto ! 

> I checked the 'cluserName:' and looks like I has messed it up somehow
> This fails which I expected.
> 'nslookup mariadb-0.mariadb-internal.default.svc.kubernetes'

Indeed, that explains the DNS resolution issues

> kubectl get endpoints mariadb-internal -n default -o yaml

Right, the connectivity is fine from the Kubernetes perspective


> Error reconciling Galera: error disabling bootstrap in Pod 0: unauthorized

We are almost there, this is the last step in the reconciliation. The `mariadb-operator` performs a request to the MariaDB sidecar agent to disable the bootstrap, as the Galera cluster has reported to be healthy.

This is most likely a RBAC issue, the `mariadb-operator` provides its service account token to authenticate in the `agent` API. The agent performs creates a `TokenReview` object to make sure its legit. The easiest way to see the problem is enabling debug logs in the `agent`:
- Edit the `StatefulSet` adding the `--log-level` flag in the `agent` sidecar container:
```yaml
 - name: agent
   image: ghcr.io/mariadb-operator/agent:v0.0.2
   args:
        - --log-level=debug
        - --addr=:5555
        - --config-dir=/etc/mysql/mariadb.conf.d
        - --state-dir=/var/lib/mysql
        - --graceful-shutdown-timeout=5s
        - --recovery-timeout=3m0s
        - --kubernetes-auth
        - --kubernetes-trusted-name=mariadb-operator
        - --kubernetes-trusted-namespace=default
```
This will show the problem straight away in the `agent` logs:
```bash
 kubectl logs mariadb-galera-0 -c agent
{"level":"info","ts":1689837187.6235018,"logger":"server","msg":"server listening","addr":":5555"}
2023/07/20 07:16:27 "DELETE http://mariadb-galera-0.mariadb-galera-internal.default.svc.cluster.local:5555/api/bootstrap HTTP/1.1" from 10.244.4.2:35182 - 200 0B in 6.558775ms
2023/07/20 07:16:27 "DELETE http://mariadb-galera-0.mariadb-galera-internal.default.svc.cluster.local:5555/api/bootstrap HTTP/1.1" from 10.244.4.2:35182 - 404 41B in 2.613441ms

kubectl logs mariadb-operator-6cff7c9764-lv9fd
{"level":"info","ts":1689837387.5999043,"logger":"galera","msg":"Galera cluster is healthy","controller":"mariadb","controllerGroup":"mariadb.mmontes.io","controllerKind":"MariaDB","mariaDB":{"name":"mariadb-galera","namespace":"default"},"namespace":"default","name":"mariadb-galera","reconcileID":"1e261e3e-fd18-4e10-8804-c7b55eb129b5"}
```

Posible reasons:
- `ClusterRoleBinding` not present. It should have been created by Helm:
``` bash
 kubectl get clusterrolebinding mariadb-galera-auth:auth-delegator
NAME                                 ROLE                                AGE
mariadb-galera-auth:auth-delegator   ClusterRole/system:auth-delegator   19m
```
- Either the `mariadb-operator` or the `agent` are not allowed to create `TokenReviews`:
```bash
kubectl auth can-i --list --as=system:serviceaccount:default:mariadb-operator | grep tokenreview
tokenreviews.authentication.k8s.io              []                                    []               [create]

kubectl auth can-i --list --as=system:serviceaccount:default:mariadb-galera | grep tokenreview
tokenreviews.authentication.k8s.io              []                                    []               [create]
```

**Comment by dbrown-auto** [comment]
Ok thank you.

This was deployed by using OLM 

The operator is unable to create tokenreviews in the default namespace but can within the operator namespace.

The mariadb-operator service account is namespaced

```
kubectl auth can-i --list --as=system:serviceaccount:default:mariadb-operator | grep tokenreview

kubectl auth can-i --list --as=system:serviceaccount:default:mariadb-galera | grep tokenreview
tokenreviews.authentication.k8s.io              []                                    []               [create]
```

I tried to modify the role but it gets reverted before I can test it :)

**Comment by mmontes11** [comment]
Thanks for the details @dbrown-auto 🙇🏻 

OLM uses the following `ClusterRole` when deploying the `MariaDBOperator` resource, which includes creating `ClusterRoles`:
- https://github.com/mariadb-operator/mariadb-operator-helm/blob/main/config/rbac/role.yaml#L54

Then, when installing the operator itself via the Helm chart, it includes an extra `ClusterRoleBinding`  `<your-operator-name>:auth-delegator` which grants permissions to create `tokenreviews`: 
- https://github.com/mariadb-operator/mariadb-operator/blob/main/deploy/charts/mariadb-operator/templates/rbac.yaml#L418..L429

Could you verify the presence of the following resources in your clusterin your cluster?
- `system:auth-delegator` `ClusterRole` 
- `<your-operator-name>:auth-delegator`  `ClusterRoleBinding` 

If any of them are missing, it would explain the problem, and you could try recreating the `MariaDBOperator` resource to see if they get recreated.

**Comment by dbrown-auto** [comment]
HI @mmontes11

Both the auth-delegators are present however it appears like it isn't delegating permissions correctly. 
```
k get clusterroles -A | grep auth-delegator
system:auth-delegator                                                  2023-07-10T02:25:08Z
```
```
k get clusterrolebindings | grep auth-delegator
mariadb-galera-auth:auth-delegator                                  ClusterRole/system:auth-delegator                                                  7d
mariadb-galera:auth-delegator                                       ClusterRole/system:auth-delegator                                                  7d
mariadb-operator:auth-delegator                                     ClusterRole/system:auth-delegator                                                  5d
mariadb:auth-delegator                                              ClusterRole/system:auth-delegator                                                  9d
```

I uninstalled the mariadb-operator to start again and noticed that the csv phase changes from 'Succeeded' to 'Installing' once I apply the operator again and just keeps restarting the 'mariadb-operator-helm-controller-manager'. 
```
NAME                                                        READY   STATUS    RESTARTS        AGE
mariadb-operator-helm-controller-manager-5c9f984b76-8tcdd   0/1     Running   7 (5m16s ago)   16m
```

I have tried the operatorhub example operator as well as the cut down version.

This is what I am working with at the moment
```
apiVersion: helm.mariadb.mmontes.io/v1alpha1
kind: MariadbOperator
metadata:
  name: mariadb-operator
  namespace: operators
spec:
  image:
    repository: ghcr.io/mariadb-operator/mariadb-operator
    pullPolicy: IfNotPresent
  logLevel: INFO
  ha:
    enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  webhook:
    enabled: true
    certificate:
      certManager: false
```

The 'mariadb-operator-helm-controller-manager' is stable but as soon as the mariadb-operator (above) is applied the OLM operator kicks in and the CSV changes.  The operator is installed as expected however the 'mariadb-operator-helm-controller-manager' never recovers.

``
time="2023-07-24T03:30:07Z" level=warning msg="unhealthy component: waiting for deployment mariadb-operator-helm-controller-manager to become ready: deployment \"mariadb-operator-helm-controller-manager\" not available: Deployment does not have minimum availability." csv=mariadb-operator.v0.18.0 id=33dOB namespace=operators phase=Succeeded strategy=deployment
I0724 03:30:07.037078       1 event.go:285] Event(v1.ObjectReference{Kind:"ClusterServiceVersion", Namespace:"operators", Name:"mariadb-operator.v0.18.0", UID:"fc576958-817a-46cf-be26-2421a5ec325b", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"8227512", FieldPath:""}): type: 'Warning' reason: 'ComponentUnhealthy' installing: waiting for deployment mariadb-operator-helm-controller-manager to become ready: deployment "mariadb-operator-helm-controller-manager" not available: Deployment does not have minimum availability.
time="2023-07-24T03:30:07Z" level=warning msg="needs reinstall: waiting for deployment mariadb-operator-helm-controller-manager to become ready: deployment \"mariadb-operator-helm-controller-manager\" not available: Deployment does not have minimum availability." csv=mariadb-operator.v0.18.0 id=vGuMB namespace=operators phase=Failed strategy=deployment
I0724 03:30:07.086772       1 event.go:285] Event(v1.ObjectReference{Kind:"ClusterServiceVersion", Namespace:"operators", Name:"mariadb-operator.v0.18.0", UID:"fc576958-817a-46cf-be26-2421a5ec325b", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"8229109", FieldPath:""}): type: 'Normal' reason: 'NeedsReinstall' installing: waiting for deployment mariadb-operator-helm-controller-manager to become ready: deployment "mariadb-operator-helm-controller-manager" not available: Deployment does not have minimum availability.
time="2023-07-24T03:30:07Z" level=info msg="scheduling ClusterServiceVersion for install" csv=mariadb-operator.v0.18.0 id=wgYoB namespace=operators phase=Pending
I0724 03:30:07.140589       1 event.go:285] Event(v1.ObjectReference{Kind:"ClusterServiceVersion", Namespace:"operators", Name:"mariadb-operator.v0.18.0", UID:"fc576958-817a-46cf-be26-2421a5ec325b", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"8229111", FieldPath:""}): type: 'Normal' reason: 'AllRequirementsMet' all requirements found, attempting install
time="2023-07-24T03:30:07Z" level=info msg="No api or webhook descs to add CA to"
I0724 03:30:07.206070       1 event.go:285] Event(v1.ObjectReference{Kind:"ClusterServiceVersion", Namespace:"operators", Name:"mariadb-operator.v0.18.0", UID:"fc576958-817a-46cf-be26-2421a5ec325b", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"8229117", FieldPath:""}): type: 'Normal' reason: 'InstallSucceeded' waiting for install components to report healthy
time="2023-07-24T03:30:07Z" level=info msg="install strategy successful" csv=mariadb-operator.v0.18.0 id=3kV1X namespace=operators phase=Installing strategy=deployment
I0724 03:30:07.274828       1 event.go:285] Event(v1.ObjectReference{Kind:"ClusterServiceVersion", Namespace:"operators", Name:"mariadb-operator.v0.18.0", UID:"fc576958-817a-46cf-be26-2421a5ec325b", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"8229123", FieldPath:""}): type: 'Normal' reason: 'InstallWaiting' installing: waiting for deployment mariadb-operator-helm-controller-manager to become ready: deployment "mariadb-operator-helm-controller-manager" not available: Deployment does not have minimum availability.
time="2023-07-24T03:30:07Z" level=info msg="install strategy successful" csv=mariadb-operator.v0.18.0 id=aQ7UR namespace=operators phase=Installing strategy=deployment
{"level":"error","ts":"2023-07-24T03:30:07Z","logger":"controllers.operator","msg":"Could not update Operator status","request":"/mariadb-operator.operators","error":"Operation cannot be fulfilled on operators.operators.coreos.com \"mariadb-operator.operators\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators.(*OperatorReconciler).Reconcile\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/pkg/controller/operators/operator_controller.go:158\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235"}
time="2023-07-24T03:30:07Z" level=info msg="install strategy successful" csv=mariadb-operator.v0.18.0 id=6DhHz namespace=operators phase=Installing strategy=deployment
time="2023-07-24T03:30:07Z" level=info msg="install strategy successful" csv=mariadb-operator.v0.18.0 id=LN55c namespace=operators phase=Installing strategy=deployment
{"level":"error","ts":"2023-07-24T03:30:07Z","logger":"controllers.operator","msg":"Could not update Operator status","request":"/mariadb-operator.operators","error":"Operation cannot be fulfilled on operators.operators.coreos.com \"mariadb-operator.operators\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators.(*OperatorReconciler).Reconcile\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/pkg/controller/operators/operator_controller.go:158\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235"}
time="2023-07-24T03:30:07Z" level=info msg="install strategy successful" csv=mariadb-operator.v0.18.0 id=uZl9K namespace=operators phase=Installing strategy=deployment
```

After reinstall (although the 'mariadb-operator-helm-controller-manager' is still broken'
neither of these can create tokenreviews now
```
kubectl auth can-i --list --as=system:serviceaccount:default:mariadb-operator | grep tokenreview
kubectl auth can-i --list --as=system:serviceaccount:default:mariadb-galera | grep tokenreview
```

Kind regards

**Comment by dbrown-auto** [comment]
Hi @mmontes11 

It was 100% what you called out first and for anyone else it was tweaked in the operator here.

[https://github.com/mariadb-operator/mariadb-operator/blob/8295963114e8305daeeab98e9472ccd8164b63aa/deploy/charts/mariadb-operator/values.yaml#L15](url)

I had some residual garbage in my operator config and it took going to the extreme of removing everything for me to notice.

@mmontes11 Thank you for your assistance!

**Comment by mmontes11** [comment]
Great! Let me know if you need further help
