### ISSUE TITLE
[Feature] Support `metadata` in `volumeClaimTemplates` 

### ISSUE THREAD

**Issue by mmontes11** [mariadb-operator/mariadb-operator#169]
**Describe the solution you'd like**
Be able to specify `metadata` in the `volumeClaimTemplates` fields, both in the MariaDB and the Galera one. This can be achieved by changing from `corev1.PersistentVolumeClaimSpec` to `corev1.PersistentVolumeClaim` in the following types:
- https://github.com/mariadb-operator/mariadb-operator/blob/a820746605ed15aadd7c969e230808ca4f5cf704/api/v1alpha1/mariadb_types.go#L104
- https://github.com/mariadb-operator/mariadb-operator/blob/a820746605ed15aadd7c969e230808ca4f5cf704/api/v1alpha1/mariadb_galera_types.go#L167

Alternatively, consider creating our own `mariadbv1alpha1.PersistentVolumeClaim`.

**Additional context**
Sometimes annotations need to be added to PVCs:
- https://www.vcluster.com/docs/architecture/storage#how-does-it-work

**Comment by vavrajosef** [comment]
I would like to work on this, please assign it to me.

**Comment by mmontes11** [comment]
Absolutely, go ahead. Reach out if you have any questions!

**Comment by vavrajosef** [comment]
I have created [PR](https://github.com/mariadb-operator/mariadb-operator/pull/175), where I replaced Spec. Please review it. Also, you were talking about changing some annotations and I have read the article in the description of this issue, but I don't think I understand what annotations should be updated.
When I forked this repository I had trouble running some tests, so I am not 100% sure my change didn't break anything.

**Comment by mmontes11** [comment]
Hey @vavrajosef, just left a [comment](https://github.com/mariadb-operator/mariadb-operator/pull/175#pullrequestreview-1553270879) in the PR regarding this!
