### ISSUE TITLE
Add ability to specify annotations for deployed statefulsets and services [Feature]

### ISSUE THREAD

**Issue by djryanj** [mariadb-operator/mariadb-operator#183]
**Is your feature request related to a problem? Please describe.**
Currently, there is no option to add annotations to the StatefulSet and Service objects that the operator deploys. This means that if we want to use e.g., linkerd, which relies upon those annotations to configure itself, we need to annotate the namespace. Other required annotations may not be able to be applied if they don't have a similar "annotate the namespace" functionality (which also may not be entirely appropriate anyway).

**Describe the solution you'd like**
At minimum, to the `MariaDB` CRD `spec`, a pair of fields:
`podAnnotations[]` (to keep with a consistent naming, the fact that it's a StatefulSet I don't think is relevant)
`serviceAnnotations[]`

These lists of strings would then get applied to the StatefulSet or Service as with other similar configurations.

**Describe alternatives you've considered**
In some cases, annotations on the namespace work. In other cases this may not be possible, so as of right now I cannot see an alternative given the nature of the controller-deployed resources.

**Additional context**
None

**Environment details**:
- Kubernetes version: 1.27.3
- mariadb-operator version: Helm chart version 0.19.0
- Install method: helm
- Install flavour: recommended

**Comment by mmontes11** [comment]
Hey ther @djryanj ! thanks for bringing this up.

We currently support adding metadata to all the reconciled children objects via the `MariaDB`'s `spec.inheritMetadata` metadata field:
https://github.com/mariadb-operator/mariadb-operator/blob/0d87ad05ad4350a29e71a541d80672c9b9785822/examples/manifests/mariadb_v1alpha1_mariadb_metadata.yaml#L7

This includes `Services` and `StatefulSets`. Would this be a fit for your use case?

**Comment by djryanj** [comment]
@mmontes11 that's a good start, though it's rather unintuitive if you ask me. Especially since it would be better to be able to target that metadata on a per-object basis since the needs might be different. 

In my case, linkerd requires the metadata annotation `linkerd.io/inject: enabled` on the pods (really, set in the `spec.template.metadata.annotation` field of the `STS` or `Deployment` or whatever), and having this metadata annotation everywhere has no effect on anything else, so the current solution of `spec.inheritMetadata` would work.

However, when dealing with linkerd's protocol detection and the specifics of MySQL, it is _sometimes_ necessary to set the metadata annotation `config.linkerd.io/opaque-ports` (see https://linkerd.io/2.13/features/protocol-detection/#marking-ports-as-opaque - this is necessary when using Galera) but that should only be set on the _destination_ (e.g., the `Service` deployed by the operator), and so having that metadata annotation everywhere might cause some bizarre and undesirable effects.

Although I don't have a specific additional use case, I can also see some possible need to annotate things specifically and uniquely instead of having all things inherit the same metadata.

**Comment by djryanj** [comment]
@mmontes11 what is the behaviour on `services` if, as in your example above, both `spec.inheritMetadada.annotations[]` and `spec.service.annotations[]` are set? Or, If `spec.inheritMetadada.annotations[]` IS set and `spec.service.annotations[]` IS NOT? Does the metadata form `spec.inheritMetadada.annotations[]` apply to the `service` object in either case?

>  we are open to add specific annotations when it's a de-facto standard accepted by the cloud native community

This is a good point, and perhaps I haven't spent enough time in the community to know, but given the prevalence of such a thing in a Helm template, that's one of the reasons I thought it was odd that it wasn't already a thing in the operator.

**Comment by mmontes11** [comment]
> what is the behaviour on services if, as in your example above, both spec.inheritMetadada.annotations[] and spec.service.annotations[] are set? 

both of them are applied, but `spec.service.annotations` takes precedence over the other, meaning that in case that the same annotation is provided the `spec.service.annotations`  overrides.

> Does the metadata form spec.inheritMetadada.annotations[] apply to the service object in either case?

it does, it applies to all children objects.

**Comment by djryanj** [comment]
@mmontes11 ok, that makes sense and within the context of my requirements is fine since the annotations applied by `inheritMetadata` won't have any effect on the `service` objects. I hope you'll consider adding this anyway. Thanks for your time!

**Comment by mmontes11** [comment]
Great, I've created the following issue:
- https://github.com/mariadb-operator/mariadb-operator/issues/186

It's labeled with `good-first-issue` and `help-wanted in case you want to give it a try. Contributions welcome!

Closing
