### ISSUE TITLE
[Question] Documentation about database Access

### ISSUE THREAD

**Issue by valentin2105** [mariadb-operator/mariadb-operator#200]
Hello,

First, thanks for this nice project, seem a good way to deploy MariaDB on Kubernetes ! 

I don't find in the README, a way to get a remote access to the database, 

I have created the demo mariadb object, the database, theuser, the grant and all seem work well, my mariadb pod is running, but when I try remote access, it doesn't work.  `permission denied`.  (for Root and User). 

My question is, how to define the Host of a grant ?

I'm sorry if it's already documented somewhere. 

Thank you

**Comment by mmontes11** [comment]
Hey there @valentin2105! Thanks for bringing this up.

> My question is, how to define the Host of a grant ?

I've just updated the example, you can specify a `spec.host` in the `Grant` resource:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/mariadb_v1alpha1_grant.yaml

By default, it will be `%`

This is a feature to be released in `v0.0.20`, so stay tuned! You can subscribe to GitHub releases or join our [Slack channel](https://join.slack.com/t/mariadb-operator/shared_invite/zt-1xsfguxlf-dhtV6zk0HwlAh_U2iYfUxw)

> but when I try remote access, it doesn't work. permission denied. (for Root and User).

Curious about this, are you getting permission denied with the Root user? Could you try to check the logs os the `MariaDB` instance to see if there something relevant there?

Thanks!

**Comment by valentin2105** [comment]
It's fixed, thank you @mmontes11  

It was by secret's base64 that wasn't created using `echo -n`.
