### ISSUE TITLE
[Question] Readonly replicas

### ISSUE THREAD

**Issue by kvaps** [mariadb-operator/mariadb-operator#202]
Hi there,
We're looking for the way of configuring a few replicas, where just one works for writes and others work for reads.

Eg. [cloudnative-pg](https://github.com/cloudnative-pg/cloudnative-pg) makes three services by default:

```bash
# k get svc -n db-pg-test
NAME      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
test-r    ClusterIP   10.103.223.229   <none>        5432/TCP   43h
test-ro   ClusterIP   10.103.103.156   <none>        5432/TCP   43h
test-rw   ClusterIP   10.98.201.65     <none>        5432/TCP   43h

# k get ep -n db-pg-test
NAME      ENDPOINTS                                       AGE
test-r    10.0.1.165:5432,10.0.2.28:5432,10.0.3.95:5432   43h
test-ro   10.0.1.165:5432,10.0.3.95:5432                  43h
test-rw   10.0.2.28:5432                                  43h

# k get pod -o wide -n db-pg-test
NAME     READY   STATUS    RESTARTS   AGE   IP           NODE   NOMINATED NODE   READINESS GATES
test-1   1/1     Running   0          43h   10.0.2.28    pve3   <none>           <none>
test-2   1/1     Running   0          43h   10.0.3.95    pve1   <none>           <none>
test-3   1/1     Running   0          43h   10.0.1.165   pve2   <none>           <none>
```

Is there any option to get the similar setup using mariadb-operator?
Does it makes sense for galera cluster?

**Comment by boedy** [comment]
Hi @kvaps, In the slack channel someone was[ asking a similar question](https://mariadb-operator.slack.com/archives/C056RAECH0W/p1687461414047109) I believe.

**Comment by mmontes11** [comment]
Hey there @kvaps ! Thanks for bringing this questions up.

I've created an issue for this:
- https://github.com/mariadb-operator/mariadb-operator/issues/203

Currrently, only the [replication](https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/mariadb_v1alpha1_mariadb_replication.yaml) HA mode modes creates an extra service to perform writes to a specific node. We are aiming to consolidate and standarize this solution for Galera as well, as it seems to be a common practise for preventing posible deadlocks.

It will be tackled in the following releases!

**Comment by kvaps** [comment]
Ok, thanks a lot!

**Comment by kvaps** [comment]
> To answer your question, here it is how are we planning to standarize Services for HA:
>
>  - `<mariadb-name>`: To be used for read requests. It will point to all nodes
>  - `primary-<mariadb-name>`: To be used for write requests. It will point to a single node.
>
> It will be tackled in the following releases!


The only wish I'd like to add is one more service:

 - `secondary-<mariadb-name>`: To be only for read requests. It should point to all nodes, except the primary one.

**Comment by mmontes11** [comment]
> The only wish I'd like to add is one more service:
secondary-<mariadb-name>: To be used only for read requests. It should point to all nodes, except the primary one.

See this [comment](https://github.com/mariadb-operator/mariadb-operator/issues/203#issuecomment-1688058047). Let's keep the discussion there. Closing
