### ISSUE TITLE
[Feature] Support for more service configuration

### ISSUE THREAD

**Issue by davidpanic** [mariadb-operator/mariadb-operator#210]
**Is your feature request related to a problem? Please describe.**

Currently the only possible configuration options for the created services are `type` and `annotations`. This is very restrictive and there is currently no way to set for example the `externalTrafficPolicy`.

Here is the CRD definition:

https://github.com/mariadb-operator/mariadb-operator/blob/7804cc922dfe3b91a2e3403075838c818a408ab8/deploy/crds/crds.yaml#L9426-L9436

**Describe the solution you'd like**

I would like to be able to set at least `externalTrafficPolicy: Local` on the service as that optimizes the network path to the pod in our setup as we use cilium's BGP service advertising.

You should also add the other service properties.

**Describe alternatives you've considered**

The alernative to this is to manually create a service, but that defeats part of the purpose of this operator.

**Environment details**:
- Kubernetes version: 1.27.1
- mariadb-operator version: 0.15.1
- Install method: helm
- Install flavour: recommended

**Comment by mmontes11** [comment]
Hey there @davidpanic ! Thanks for bringing this up.

I would agree that this is something we should support.

Regarding the implementation, it should be quite straightforward:
- Add the new field(s) to be supported in the `Service` type:
https://github.com/mariadb-operator/mariadb-operator/blob/7804cc922dfe3b91a2e3403075838c818a408ab8/api/v1alpha1/mariadb_types.go#L69

- Adapt the `BuildService` function
https://github.com/mariadb-operator/mariadb-operator/blob/7804cc922dfe3b91a2e3403075838c818a408ab8/pkg/builder/service_builder.go#L33

- Find all the references of `BuildService`  and pass the right options

This has been labeled with `help wanted` and `good first issue`. PRs welcome!
