### ISSUE TITLE
[Bug/Suggestion] When deploying multiple galera CRs with same name to same cluster, only one is working (without overrides)

### ISSUE THREAD

**Issue by Guzzi** [mariadb-operator/mariadb-operator#213]
**Describe the bug**
when deploying multiple galera CRs with the same name to same cluster, only one is working (without applying specific overrides).
This is caused by the fact, that the role binding is using the CR name - so when the same CR name exists e.g. in multiple namespaces, only one works properly, the otheres do not. 
This scenario is not uncommon, when e.g. depoloying multiple environments to different namespaces.
This known problem can be workarounded by overriding the authDelegatorRolename in the spec - but the current default behaviour of the operator will run into problems and a user has to look deep into documentation and troubleshooting guide to find this requirement.
I would suggest to include the namespace into the role name in addition to the CR name as default - as this would avoid such conflicts and allow the operator to work as intended without the user requiring to set specific overrides.

**Comment by mmontes11** [comment]
Hey there!

Neat suggestion! I think it would be very benefical.

To be included in `v0.0.20`
