### ISSUE TITLE
[Bug] v0.0.19 Release manifests reference the previous version

### ISSUE THREAD

**Issue by gg-kialo** [mariadb-operator/mariadb-operator#217]
**Describe the bug**

The generated manifests included in the [v0.0.19 release](https://github.com/mariadb-operator/mariadb-operator/releases/tag/v0.0.19) reference the v0.0.18 image tag and v0.18.0 helm chart.

The git history looks like:

```
* a820746 Bump helm chart (helm-chart-0.19.0 release)
* 5ef0970 Bump init container version (v0.0.19 release)
|
* previous commits
```

**Expected behaviour**
The generated manifests for v0.0.19 should use the v0.0.19 image.

**Steps to reproduce the bug**
N/A

**Additional context**

I am vendoring these manifests in my repo and using renovate to pull in the new versions as they are released.
Due to these manifests referencing the previous version, I am lagging a release behind.

As the manifests are generated from the helm chart, perhaps they should be released as part of the helm-chart release instead of as part of the executable version release. 

**Environment details**:
- Kubernetes version: -
- mariadb-operator version: 0.0.19
- Install method: static manifests
- Install flavour: minimal, recommended

**Comment by mmontes11** [comment]
Hey there @gg-kialo ! Good catch, thanks for bringing this up.

> As the manifests are generated from the helm chart, perhaps they should be released as part of the helm-chart release instead of as part of the executable version release.

Your suggestion makes total sense, will fix this in the `v0.0.20` release

**Comment by mmontes11** [comment]
We have introduced a new [Manifests](https://github.com/mariadb-operator/mariadb-operator/blob/main/.github/workflows/manifests.yml) workflow that will render the manifests and attach them to the helm chart release. 

See [helm-chart-0.19.0](https://github.com/mariadb-operator/mariadb-operator/releases/tag/helm-chart-0.19.0) as an example. Closing!

Thanks for the suggestion 🙏🏻

**Comment by gg-kialo** [comment]
That's great, thanks. :pray:
