### ISSUE TITLE
[Bug] Remove old dependency to sigs.k8s.io/controller-runtime and sigs.k8s.io/controller-runtime/pkg/envtest/printer

### ISSUE THREAD

**Issue by mhuin** [mariadb-operator/mariadb-operator#225]
the mariadb operator module has a dependency to envtest/printer that has been dropped in recent versions of controller-runtime: https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.14.0

When importing the mariadb-operator module in other projects, go mod returns an error due to this:

'''go: downloading sigs.k8s.io/controller-runtime v0.16.1
XXX/controllers imports
	github.com/mariadb-operator/mariadb-operator/pkg/client imports
	github.com/mariadb-operator/mariadb-operator/api/v1alpha1 tested by
	github.com/mariadb-operator/mariadb-operator/api/v1alpha1.test imports
	sigs.k8s.io/controller-runtime/pkg/envtest/printer: module sigs.k8s.io/controller-runtime@latest found (v0.16.1), but does not contain package sigs.k8s.io/controller-runtime/pkg/envtest/printer'''

A solution could be either to add the removed code to mariadb-operator ( https://github.com/kubernetes-sigs/controller-runtime/pull/1977/files ) or upgrade to ginkgo v2.

**Comment by mmontes11** [comment]
Hey there @mhuin ! Thanks for bringing this up

I think it makes sense to upgrade to ginkgo v2, actually, it is in our radar:
- https://github.com/mariadb-operator/mariadb-operator/issues/3

We will tackle this in the next release  👍🏻 

Out of curiosity, what is your use case for consuming `mariadb-operator` as a package?

**Comment by mhuin** [comment]
> Out of curiosity, what is your use case for consuming `mariadb-operator` as a package?

My team is writing an operator for the Software Factory project ( https://www.softwarefactory-project.io ), mariadb is a dependency for some of our services. Being new to operator development, we were experimenting with deploying mariadb programmatically in our controller via the operator. In the end we chose to keep things simple by using a simple deployment of a mariadb container; we just kept the database connection secret's structure from the mariadb operator in case we opt to use it later. The package was used to compute the DSN; it was trivial to drop that dependency but I thought you might want to know about this issue.

**Comment by mmontes11** [comment]
Thanks for the context @mhuin ! 

> The package was used to compute the DSN;

That makes sense, packages are there to be reused 👍🏻 

>  it was trivial to drop that dependency but I thought you might want to know about this issue.

Yes indeed, thanks for letting me know, I'm aiming to bump to the latest `controller-runtime` and `gingko` versions in this release.

> we were experimenting with deploying mariadb programmatically in our controller via the operator. In the end we chose to keep things simple by using a simple deployment of a mariadb container

Happy to provide some guidance in case you decide to finally use the operator. Just open another issue or drop a message in our [slack](https://join.slack.com/t/mariadb-operator/shared_invite/zt-1xsfguxlf-dhtV6zk0HwlAh_U2iYfUxw) channel
