### ISSUE TITLE
[Bug] initcontainer spec collides with kustomize imagetagtransformer

### ISSUE THREAD

**Issue by Guzzi** [mariadb-operator/mariadb-operator#226]
Hi @mmontes11 ,
I just tested 0.20 release with the initcontainers spec and run into a problem when using kustomize for overlay overrides.
If I add the imageTagTransformer in the overlay, I get an error and the manifests cannot be rendered by kustomize:

Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `kustomize build .cgroup/ctraffic/overlay/azure-dev1` failed exit status 1: Error: wrong Node Kind for expected: ScalarNode was MappingNode: value: {pullPolicy: IfNotPresent repository: mariadb tag: 10.11.5}

https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_imagetagtransformer_

It seems, that kustomize interprets the image spec as standard kubernetes image definition and this has a different data structure than the one in the mdb operator (image: source:tag versus image:{properties})

initContainers:
    - image:
        repository: mariadb
        tag: "10.11.5"
        pullPolicy: IfNotPresent

To be compatible with kustomize imageTagTransformer either the object for image should comply to the standarf image object - or should have a different naming I suppose - what do you think?

**Comment by mmontes11** [comment]
Hey there @Guzzi ! Thanks for bringing this up.

> To be compatible with kustomize imageTagTransformer either the object for image should comply to the standarf image object - or should have a different naming I suppose - what do you think?

That makes complete sense. We should align with the `Pod` specification to better integrate with tools like kustomize.

This will require breaking changes though, but I think it still worth it.

**Comment by Guzzi** [comment]
Hi @mmontes11 ,
any chance to get this change released? Without it, I am unable to integrate mdb into kustomize which collides with the current object definitions. If you hesistate to apply breaking change, you could rename the mdb objects, so they do not collide with default kubernetes object names!?

**Comment by mmontes11** [comment]
Hey there @Guzzi ! I will try to squeeze it in `v0.0.21`. 

> f you hesistate to apply breaking change, you could rename the mdb objects, so they do not collide with default kubernetes object names!?

That's actually a good suggestion, and actually the strategy followed by CNPG:
- https://cloudnative-pg.io/documentation/1.16/quickstart/

The downside I guess is that we will be losing integration with tooling like kustomize.

**Comment by Guzzi** [comment]
Hi @mmontes11 , not fully true - you'll not be able to use the imagetagtransformer from kustomize, but of course you always can use 'patches' to override the values - so if you want to be able to use the imagetagtransformer, you'd have to keep using the image object (name), but use the standard kubernetes object structure for images - if you rename it to something else, you won't be able to use the imagetagtransformer anymore, but avoid the compatibility issue with kustomize overlay is using the imagetagtransformer (e.g. for other manifests) and have to use a kustomize 'patch' to override e.g. the image tag for the mdb cr. I am fine with either solution - and thanks for your great support!

**Comment by mmontes11** [comment]
Hey there @Guzzi. Thanks a lot for your input, very much appreciated.

The PR for supporting the standard Kubernetes object is ready:
- https://github.com/mariadb-operator/mariadb-operator/pull/248

Could you please take a look at the migration described there to see if this is what you expect? 🙏🏻

**Comment by Guzzi** [comment]
Hi @mmontes11,
thanks for the update. As far as I have experienced the imagetagtransformer, it seems to only be aplied to image objects within containers/initcontainers - but yes, object type should be ok like this - looks the same like within e.g. kubernetes depployment - so I would think it should work this way.

**Comment by mmontes11** [comment]
great to hear @Guzzi , `v0.0.21` has been released with this change
