### ISSUE TITLE
[Feature] Allow setting ServiceAccountName / don't use "default" ServiceAccount

### ISSUE THREAD

**Issue by Nold360** [mariadb-operator/mariadb-operator#244]
**Is your feature request related to a problem? Please describe.**
When applying security policies like "no default service account name", currently the only way to do this is by creating a galera cluster. 

https://github.com/mariadb-operator/mariadb-operator/blob/b25c694a80d1064de120d623fede25824af9eda5/pkg/builder/statefulset_builder.go#L180-L187

**Describe the solution you'd like**
I would like to either set the name manual, or just set a "random" name in `buildStsServiceAccountName` when not galera.

**Describe alternatives you've considered**
Alternative is deploying galera cluster. but you might not want to do that.

**Additional context**
-

**Environment details**:
- Kubernetes version: 1.26
- mariadb-operator version: latest (0.20.0)
- Install method: helm
- Install flavour: custom (i guess)

**Comment by Nold360** [comment]
Why can't we always do `serviceAccount = mariadb.Name ` ?

**Comment by mmontes11** [comment]
Hey @Nold360 ! Thanks for opening this 

>  Why can't we always do serviceAccount = mariadb.Name  ?

That could be valid, basically we can set `serviceAccount = mariadb.Name` and `AutomountServiceAccountToken = false` here:
https://github.com/mariadb-operator/mariadb-operator/blob/b25c694a80d1064de120d623fede25824af9eda5/pkg/builder/statefulset_builder.go#L118

But if we do that, we will need to create the `ServiceAccount` always, in a non conditional way here:
https://github.com/mariadb-operator/mariadb-operator/blob/b25c694a80d1064de120d623fede25824af9eda5/pkg/controller/rbac/controller.go#L28

We could move down the `!mariadb.Galera().Enabled` condition, something like:
```golang
func (r *RBACReconciler) Reconcile(ctx context.Context, mariadb *mariadbv1alpha1.MariaDB) error {
	key := client.ObjectKeyFromObject(mariadb)
	sa, err := r.reconcileServiceAccount(ctx, key, mariadb)
	if err != nil {
		return fmt.Errorf("error reconciling ServiceAccount: %v", err)
	}

	if !mariadb.Galera().Enabled {
		return nil
	}
	role, err := r.reconcileRole(ctx, key, mariadb)
	if err != nil {
		return fmt.Errorf("error reconciling Role: %v", err)
	}
        ...
}
```

Would you mind open a PR? 

Thanks!

**Comment by chinmaym07** [comment]
Hi @mmontes11 can I contribute to this ?

**Comment by mmontes11** [comment]
Hei @chinmaym07 ! please go ahead and let me know if you need any help.
