### ISSUE TITLE
[Bug] Multiple Bugs in the OLM operator

### ISSUE THREAD

**Issue by dimidevops** [mariadb-operator/mariadb-operator#251]
**Describe the bug**
<p>

1. When creating a MariaDB instance via the OLM operator the YAML template is not updated to reflect the new changes in the 0.21.0 version. Template provided YAML is referencing old 0.20.0 OLM. 
![YAML reference](https://github.com/mariadb-operator/mariadb-operator/assets/147745543/83fcfd4c-1801-4fce-9193-66ee43ab15fe)

2. After creating a MariaDB instance with metrics enabled the necessary labels are not set on the service and prometheus cannot find the targets.
![Service_missing_labels](https://github.com/mariadb-operator/mariadb-operator/assets/147745543/009c0e65-61cc-4285-8206-9e5b882dffc3)
![Metrics_missing](https://github.com/mariadb-operator/mariadb-operator/assets/147745543/d8a190bd-eab0-4228-a042-a306f4bed509)

3. The pod that is created in openshift-operators "mariadb-operator-helm-controller-manager" keeps crashing frequently and enters in crashloopbackoff state. I've attached the logs.
[mariadb-operator-helm-controller-manager-b6f868cc-zmdnh-manager(1).log](https://github.com/mariadb-operator/mariadb-operator/files/12885898/mariadb-operator-helm-controller-manager-b6f868cc-zmdnh-manager.1.log)

**Is the bug related to Galera?** NO
- [x] I have checked the [Galera documentation](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/GALERA.md)
- [X] I have checked the [Galera troubleshooting guide](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/GALERA.md#troubleshooting)

**Expected behaviour**

**Steps to reproduce the bug**

Tried removing the OLM and namespace then installing again. Result is always the same.

**Additional context**

OLM is installed for all namespaces into openshift-operator namespace
**Environment details**:
- Kubernetes version: AWS ROSA (OpenShift 4.13.14)
- mariadb-operator version: 0.21.0
- Install method: OLM
- Install flavour: recommended

**Comment by mmontes11** [comment]
Hey there @dimidevops ! 

Regarding 1 and 2, I will be releasing a hotfix, thanks for reporting this!

Then regarding 3.
> {"level":"error","ts":1697130379.7503307,"msg":"Reconciler error","controller":"mariadboperator-controller","object":{"name":"mariadb-operator","namespace":"keycloak-sso"},"namespace":"keycloak-sso","name":"mariadb-operator","reconcileID":"6a4408b2-5432-4f26-b365-21138a2a0823","error":"Operation cannot be fulfilled on mariadboperators.helm.mariadb.mmontes.io \"mariadb-operator\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}

I do see some of these logs, which is something in our radar and will be solved in further releases. Basically, we generate the webhook certificate from helm, which is causing the resource to be updated on every render:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/deploy/charts/mariadb-operator/templates/webhook-config.yaml#L7

But as far as I know this shouldn't be causing the operator to crash, it must be something else. Maybe memory/cpu pressure? Have you tried bumping the resources?

**Comment by dimidevops** [comment]
Hey,

Thanks for the hotfixes, hope we see them live in the Operator Store soon!

There were 26 crashes before increasing the mem limits. I've edited the ClusterServiceVersion to set 512Mi mem limits for the mariadboperator-controller pod and I will let you know tomorrow if there are any restarts. From the metrics I can see that the constant updates are causing mem spikes that in turn might have caused the crashes. 
![image](https://github.com/mariadb-operator/mariadb-operator/assets/147745543/01ce81d2-8db9-4283-b048-402e68f669f0)

Another thing I've noticed is when the CSV is updated manually from the browser it doesn't delete the old replica set but it scales it to 0 and it is left like that. 
![image](https://github.com/mariadb-operator/mariadb-operator/assets/147745543/6fb5b589-8b15-479a-9b39-73a8c8aeede5)

Suggestion for future releases, if possible to make the operator clean up after any updates.

**Comment by mmontes11** [comment]
> Thanks for the hotfixes, hope we see them live in the Operator Store soon!

Hey,  yep, I don't think they will take too long. Here the first of them in case you want to have a look:
- https://github.com/mariadb-operator/mariadb-operator/pull/252

They will be released in `v0.0.22`

> There were 26 crashes before increasing the mem limits. I've edited the ClusterServiceVersion to set 512Mi mem limits for the mariadboperator-controller pod and I will let you know tomorrow if there are any restarts. 

Great, let me know if that solves the crashes. I will bump the default memory limit to 512Mi as well.

> From the metrics I can see that the constant updates are causing mem spikes that in turn might have caused the crashes.

Not sure if this memory footprint is expected in helm based operators. In any case, from our side we will avoid re-rendering the certificates here:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/deploy/charts/mariadb-operator/templates/webhook-config.yaml#L6

Instead, we could achieve this by using from a cert controller to generate self-signed certs and inject the bundle into the webhook configurations. This may be a save in performance, as we won't be rendering certs the whole time. This should be something we will looking into soon-ish.


> Another thing I've noticed is when the CSV is updated manually from the browser it doesn't delete the old replica set but it scales it to 0 and it is left like that.
> Suggestion for future releases, if possible to make the operator clean up after any updates.

Agreed this is not ideal. Unfortunately this behaviour is not handled in our side, so probably opening an issue to OLM/operator-sdk?

**Comment by dimidevops** [comment]
Hello,

No restart since I set the limits to 512Mi, that seems to solve the constant crashing issue. 
![image](https://github.com/mariadb-operator/mariadb-operator/assets/147745543/e4bdc2b6-724b-4b34-a44e-6e12d9219021)

I don't know if there is a difference in memory usage between OLM and Helm based installation. I've only tested with OLM installation.
![image](https://github.com/mariadb-operator/mariadb-operator/assets/147745543/45c858d8-35b8-485c-b6b1-675338269748)

> Instead, we could achieve this by using from a cert controller to generate self-signed certs and inject the bundle into the webhook configurations. This may be a save in performance, as we won't be rendering certs the whole time. This should be something we will looking into soon-ish.

Yes, this is the way to go. I believe I've seen this in "Red Hat OpenShift distributed tracing platform" and "Keycloak" OLM operators. 

My Go knowledge is limited and I'm afraid I cannot assist with coding it but I can help test and find bugs like this.

> Agreed this is not ideal. Unfortunately this behaviour is not handled in our side, so probably opening an issue to OLM/operator-sdk?

I think that is part of the Deployment config and by setting it to 0 it should "auto clean up"

`spec.revisionHistoryLimit: 0 # Default to 10 if not specified`

Ref: https://stackoverflow.com/questions/37255731/clean-up-replica-sets-when-updating-deployments
Ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit

**Comment by dimidevops** [comment]
Hey @mmontes11 

Thanks for creating the issue.

I don't know if you can utilize the existing cert-manager-operator provided by RedHat that is used to manage cluster wide certificates, to setup necessary TLS for the mariadb-operator webhook . *Just a suggestion idk if it's possible*

![image](https://github.com/mariadb-operator/mariadb-operator/assets/147745543/7eab9682-419e-4893-9ddc-7aa66ebba9a7)

Ref: https://github.com/openshift/cert-manager-operator/blob/master/README.md

**Comment by mmontes11** [comment]
Hey @dimidevops ! 

Yes, it is supported, it is actually the [recommended](https://github.com/mariadb-operator/mariadb-operator#recommended-installation) installation. You can enable it by setting [`webhook.certificate.certManager = true`](https://github.com/mariadb-operator/mariadb-operator/blob/main/deploy/charts/mariadb-operator/values.yaml#L100)

This might help with the performance issue, as no certificates will be rendered:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/deploy/charts/mariadb-operator/templates/webhook-config.yaml#L8

We aim to support the cert-controller anyway, to not depend on external dependencies like cert-manager.

**Comment by mmontes11** [comment]
Fixes has been merged:
- https://github.com/mariadb-operator/mariadb-operator/pull/252
- https://github.com/mariadb-operator/mariadb-operator-helm/pull/9

They will be released in `0.22.0` later today.

**Comment by mmontes11** [comment]
@dimidevops `0.22.0` will be available in the OpenShift after these PRs get merged:
- https://github.com/k8s-operatorhub/community-operators/pull/3373
- https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3434

**Comment by dimidevops** [comment]
@mmontes11 Thank you for making this happen!
