### ISSUE TITLE
StatefulSet instances exit with exit code 0 when the `GracefulNodeShutdown` feature gate is used

### ISSUE THREAD

**Issue by comminutus** [mariadb-operator/mariadb-operator#253]
**Describe the bug**
A `mariadb-operator` Galera database is deployed with 4 replicas.  The deployment results in 4 StatefulSet pods.  If the [`GracefulNodeShutdown` Kubernetes feature gate](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/) is being utilized, when a node running one of the StatefulSet pods shuts down or is rebooted, it causes the Galera StatefulSet pod to exit with status _Completed_.  The _Completed_ status occurs when the pod exits with status code 0.

If a pod is in the _Completed_ state, it isn't restarted.  Kubernetes thinks this pod is "done," or in other ords "finished successfully" and therefore is never restarted.  A _Completed_ pod is counted in the total of replicas online. The effect this has on a Galera deployment is that the StatefulSet pod, which should be participating in an HA Galera cluster, is never restarted and never rejoins the cluster _automatically_.

To get the pod to join the cluster again, one has to manually delete the pod, signaling to Kubernetes that the replica count has decreased by one from the desired replica count, which triggers the Kubernetes scheduler to start another StatefulSet pod on the node.

This issue is a continuance of the Slack discussion found here: https://mariadb-operator.slack.com/archives/C056RAECH0W/p1697137995945069

**Expected behaviour**
StatefulSet Galera pods should rejoin the HA cluster after a reboot.

Perhaps the pod should not exit with status code 0, which would result in the pod being in the _Failed_ state. Following the node coming back online, the pod would be redeployed correctly.

**Steps to reproduce the bug**
The [`GracefulNodeShutdown` feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) is enabled by default in all Kubernetes implementations since v1.21.  However, its effect is moot unless the kubelet configuration parameters `ShutdownGracePeriod` and `ShutdownGracePeriodCriticalPods` are set above 0, since the default is 0, as described in the [Kubernetes Blog article detailing their use](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/#how-do-i-use-it).

In [Racher k3s](https://k3s.io/), this can be enabled by creating a configuration YAML file with the following contents:
```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
shutdownGracePeriod: 90s,
shutdownGracePeriodCriticalPods: 30s
```
This file can then be placed on a new node in `/etc/rancher/k3s` prior to k3s installation.  Finally, when installing k3s, pass the argument `--kubelet config=/etc/rancher/k3s/kubelet.yaml` to the k3s CLI in order to include the kublet configuration file during installation.

Once a node with this configuration is online, ensure a Galera StatefulSet pod is deployed and running on it.

To reproduce the problem, trigger a shutdown or restart on the node containing the modified kubelet configuration: `systemctl restart`.

Once the node restarts, observe the Galera pod in the _Completed_ state: `kubectl get pods -o wide` .

To restart the pod: `kubelete delete <galera pod with Completed state`

**Environment details**:
- Kubernetes version: v1.27.5+k3s1
- mariadb-operator version: 0.20.0
- Install method: helm
- Install flavour: recommended

**Comment by comminutus** [comment]
This looks related to, if not the same problem as, https://github.com/kubernetes/kubernetes/issues/118310 .  Related PR for Kubernetes has been merged (https://github.com/kubernetes/kubernetes/pull/120398) but as of the time of this writing it is not yet backported to Kubernetes 1.27 (which is what I'm using via k3s).

**Comment by mimowo** [comment]
FYI: the fix https://github.com/kubernetes/kubernetes/pull/120398 is merged in, and will be released in 1.29. We are going to proceed with cherry-picks. In the meanwhile @comminutus are you able to test the master branch if it fixes your issue?

**Comment by comminutus** [comment]
@mimowo we actually were able to upgrade to k3s v1.28.2+k3s1 which I believe is Kubernetes 1.28.2 and the problem seems to have gone away.  I'm guessing the fix was cherry-picked already into this line?  It'd be difficult for us to test the main line since we are downstream consumers via k3s, but I'll happily test any new k3s version that would also include the fix from the upstream.

**Comment by comminutus** [comment]
Fixed with https://github.com/kubernetes/kubernetes/issues/118310
