### ISSUE TITLE
[Bug] delete and recreate db with metrics - metrics password mismatch 

### ISSUE THREAD

**Issue by jurlwin** [mariadb-operator/mariadb-operator#255]
It seems that I have a password mismatch between the metrics secret and the metrics password in the database.

I have tried this multiple times and it doesn't matter if i'm using a restore (my first thought was a restore over-writing a password set) so I simplified and didn't restore the database and the metrics password was still off.

Resetting the database metrics password to the same as the secret resolves the issue.

I'm using longhorn as storage with a PVC.  The storage PVC is **not** deleted between runs -- not sure if this is really an underlying longhorn issue or a bug in the initialization.   I'm using a simple database, so far, no replication, 1 instance, no galera, etc.   Please let me know if you want me to post the yaml.  

1) Create Database mariadb2 
2) Wait for startup, all seemingly good
3) delete the database
> kubectl delete -f mariadb2.yaml
4) wait for deletion
5) Re-create the database.

> kubectl apply -f mariadb2.yaml

On a brand new database, no PVC pre-created, I see the metrics warning a single time, if I re-use the PVC, I get this until i reset the password.

```
2023-10-15  0:28:50 66 [Warning] Access denied for user 'mariadb2-metrics'@'127.0.0.1' (using password: YES)
2023-10-15  0:29:20 73 [Warning] Access denied for user 'mariadb2-metrics'@'127.0.0.1' (using password: YES)
2023-10-15  0:29:50 80 [Warning] Access denied for user 'mariadb2-metrics'@'127.0.0.1' (using password: YES)
```

k3s v1.26.6+k3s1
operator version 0.22 installed with Helm
longhorn storage

**Comment by soapiestwaffles** [comment]
I am experiencing this issue as well. new PVCs, no pre-existing CMs or Secrets

**Comment by henrywhitaker3** [comment]
Just had this too, deleting the `metrics-config` secret and deleting the metrics pod resolved this

**Comment by mmontes11** [comment]
Hey there thanks for reporting this!

It looks like you have a dirft in your metrics password. We have handled this case in `v0.0.30` so you don't need to recreate the config.
