### ISSUE TITLE
[Bug] Update from v0.20 to v0.21 fails with existing mariadb object (OLM)

### ISSUE THREAD

**Issue by ibotty** [mariadb-operator/mariadb-operator#257]
**Describe the bug**

**Is the bug related to Galera?**
No

**Expected behaviour**

The new operator csv does not install successfully because the old CRD has an incompatible field type `spec.image`.  It changed from an object to a string.

**Steps to reproduce the bug**
Create a `mariadb` object (note: `spec.image` is required) with operator version 0.20 and update to 0.21.

Can I just remove all `mariadb` objects and recreate them after the update is completed?  Does it delete the running databases?

**Comment by ibotty** [comment]
The problem is, that I can't update the manifests, because the old CRDs are still installed.  I guess that the new CRDs can't be installed because the old objects don't confirm to the new CRD.  Looks like a catch-22.

Maybe this does not happen with the operator being installed with helm, but with OLM it does not work.

**Comment by vrzlev** [comment]
Yes, I was lucky I didn't have to care about downtime. Deleted the custom objects and ran

```
kubectl replace -f https://raw.githubusercontent.com/mariadb-operator/mariadb-operator/main/deploy/crds/crds.yaml
```

After a while, Flux managed to reconcile. Using Helm under the hood didn't help.

I guess this is the price of using alpha APIs.

**Comment by ibotty** [comment]
I wonder, whether I'll have to dump and restore the DB.  I don't mind some downtime, but I'd rather not lose the mysql data dir.

**Comment by vrzlev** [comment]
For me the persistent volume claim stayed in place and got picked up again by the same MariaDB (with the same name and same namespace). But make a backup if it's production data. YMMV.

**Comment by spammads** [comment]
Had the same problem. I guess the CRD-Schema did not change so Flux doesnt know it should replace the CRDs. I yeeted all CRDs and the deployments. Than let Flux reconcile and everything came back up. I use local-storage as a PVC. Dont know if this helped. I would have had a backup in case this wouldnt have worked. Best luck to you. I'm on this operator for over a year now. It is breaking frequently.

**Comment by mmontes11** [comment]
Hey there, sorry to hear that you are experienced problems with the migration. Unfortunately we are still in alpha version and shaping the API of our CRDs, so sometimes we have to introduce breaking changes. As mentioned in this thread, here it is the migration guide:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/UPGRADE_v0.0.21.md

> Maybe this does not happen with the operator being installed with helm, but with OLM it does not work.

I will give it a try but at the very end, our helm based OLM operator installs our helm chart programatically, so there should be a way to achieve this. Probably you will need to downscale the OLM operator itself to avoid conflicts while updating the Helm release manually. Have you tried this out?

> I guess that the new CRDs can't be installed because the old objects don't confirm to the new CRD

No. This won't be a problem. CRD installations don't depend on the current objects. When you install a need CRD version, the old fields get wiped out and then you perform the migrations as indicated in the migration guide to conform to the new CRD version.

> For me the persistent volume claim stayed in place and got picked up again by the same MariaDB 

Yes! As long as you don't delete the PVCs, you won't loose the mysql data dir, as they will be reused by the new MariaDB instance.

**Comment by jbperrin88** [comment]
Hello there,

I've something closed to this .
I've also try to upgrade with OLM. 
I've followed all breaking change guide ... but I got a really short timing. 
I think it works but I've deleted mutatingwebhookconfiguration and validatingwebhookconfiguration

Do you know how can i restore a nice and clean situation ? 

Best regards
