### ISSUE TITLE
[Feature] - add possibility for sidecar containers

### ISSUE THREAD

**Issue by Guzzi** [mariadb-operator/mariadb-operator#260]
Hi @mmontes11 , as discussed on Slack: We need the possibility for sidecar containers - similar to the init containers that are already possible.
I wanted to add a monitoring client (pmm-client) as sidecar - tried to use the "metrics" section of the cr - but this one seems specialized for the mysql exporter and doesn't work for other containers. 
Can we have the possibility to add "standard" sidecars to get the possibility to add such scenarios?
And as a side note: the init containers are missing the "name" field - not a big issue, but doesn't allow to show the init container name.

Related stlack thread:
- https://mariadb-operator.slack.com/archives/C056RAECH0W/p1697298500893959

**Comment by mmontes11** [comment]
Hey! As mentioned in this [thread](https://mariadb-operator.slack.com/archives/C056RAECH0W/p1697300806426909?thread_ts=1697298500.893959&cid=C056RAECH0W), we could extend our [PodTemplate](https://github.com/mariadb-operator/mariadb-operator/blob/6e4845fe94901479be0831a3dd934cb16f308852/api/v1alpha1/base_types.go#L63) object to support adding sidecar containers, the same way we do currently with `InitContainers`:

```go
type PodTemplate struct {
	ImagePullSecrets []corev1.LocalObjectReference `json:"imagePullSecrets,omitempty" webhook:"inmutable"`

	InitContainers []ContainerTemplate `json:"initContainers,omitempty"`
	SidecarContainers []ContainerTemplate `json:"initContainers,omitempty"`

	PodSecurityContext *corev1.PodSecurityContext `json:"podSecurityContext,omitempty"`

	Affinity     *corev1.Affinity    `json:"affinity,omitempty"`
	NodeSelector map[string]string   `json:"nodeSelector,omitempty"`
	Tolerations  []corev1.Toleration `json:"tolerations,omitempty"`

	Volumes []corev1.Volume `json:"volumes,omitempty" webhook:"inmutable"`
}
```

**Comment by Guzzi** [comment]
Hi @mmontes11 , that would be great ! - beside the usecase of e.g. monitoring client it would also allow physical backups until they're back within the operator (as they need to run within the pod itself)

**Comment by MartinWeise** [comment]
I would like to offer implementation help since we use the operator at [DBRepo](https://www.ifs.tuwien.ac.at/infrastructures/dbrepo/latest/) and need a sidecar for .csv import/export to minIO. We are happy with the CRDs so far and want to use the operator as main mechanism to deploy databases.
