### ISSUE TITLE
[Feature] Add priorityClassName for operator and for deployed pods that are part of Mariadb CRD

### ISSUE THREAD

**Issue by mnbro** [mariadb-operator/mariadb-operator#265]
**Is your feature request related to a problem? Please describe.**
If in a k8s cluster I have priority classes, including a default one, after bootstrapping mariadb-operator its pods will fail in the default one which usually have a low priority so in case of resource pressure they will be evicted.

**Describe the solution you'd like**
Allow setting priorityClassName for operator and for deployed pods that are part of Mariadb CRD.

**Describe alternatives you've considered**
Deployment for mariadb-operator can be manually edited to include priorityClassName but is not a nice solution.
For Mariadb CRD I have tried mutating pods using kyverno/gatekeeper but in case a pod is killed it will never be recreated.

**Additional context**

**Environment details**:

**Comment by mmontes11** [comment]
Hey there @mnbro ! This makes complete sense to me.

It should be easy to achieve by extending the `PodTemplate` type:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/api/v1alpha1/base_types.go#L63

and also the `StatefulSet` builder:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/pkg/builder/statefulset_builder.go

PRs welcome!

**Comment by mmontes11** [comment]
@mnbro this is definetly a good chance! refer to our dev guide for setting up the environment:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/DEVELOPMENT.md
