### ISSUE TITLE
[Bug] Failover breaks replication if a super privileged user writes data during failover

### ISSUE THREAD

**Issue by harunkucuk5** [mariadb-operator/mariadb-operator#291]
**Describe the bug**

We make the active primary read-only before failing it over. However, this is not enough to keep the data safe if there is a user that has SUPER privileges. So if a user has the SUPER privilege it can write to the database even if the database is read-only. So in that case when we mark the active primary read-only the current primary still accepts write requests from these users and when the switchover is complete the new master will be missing these data and the gtid position will be wrong when connecting the old primary as a replica to the new primary and the replication stream gets broken with the following error or another conflict

```bash
Last_SQL_Errno: 1062
                Last_SQL_Error: Could not execute Write_rows_v1 event on table test.users; Duplicate entry '15799' for key 'PRIMARY', Error_code: 1062; handler error HA_ERR_FOUND_DUPP_KEY; the event's master log mariadb-cluster-bin.000001, end_log_pos 192
```

**Is the bug related to Galera?**
No, it is related to the traditional MariaDB replication, not to Galera.

- [x] I have checked the [Galera documentation](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/GALERA.md)
- [x] I have checked the [Galera troubleshooting guide](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/GALERA.md#troubleshooting)

**Expected behavior**

When failover is started the active primary must not accept any write transaction from any user to keep the data unchanged. This can be done with the following command that described [here](https://mariadb.com/kb/en/flush/#purpose-of-flush-tables-with-read-lock:~:text=Purpose%20of%20FLUSH%20TABLES%20WITH%20READ%20LOCK%C2%B6)

```bash
flush tables with read lock;
```

**Steps to reproduce the bug**

Create a basic table

```bash
 CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=15802 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
```

Create a simple bash script to write this table,

```bash

#!/bin/bash

while true; do
    # Generate random values for username and email
    username=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8)
    email="${username}@example.com"

    # MySQL query to insert data into the 'users' table
    query="INSERT INTO users (username, email) VALUES ('$username', '$email');"

    # Execute the query using the mysql command
    mysql -u root -p${MARIADB_ROOT_PASSWORD} -h mariadb-cluster-primary -D test -e "$query"

    # Adjust the sleep duration based on how frequently you want to insert data
    sleep 1
done

```

run this script and while it is running perform a manual or automatic failover

```bash
./test_script
````

**Comment by mmontes11** [comment]
Thanks for reporting this @harunkucuk5 ! 

Your proposal totally makes sense, `FLUSH TABLES WITH READ LOCK;` was actually present in the first implementation of replication. We opted to go for a more permissive approach with `readonly` after facing issues where the operator was struggling to reconcile replication, as it was in an intermediate state where the tables were locked.

I think `readonly` may be good enough for uses cases where the clients have a restricted amount of permissions, not including `SUPER`, so they can't actually bypass `readonly`. That might not be always the case, so I still see the benefit of `FLUSH TABLES WITH READ LOCK;`

What about exposing this to the user in a new field with propper documentation?:

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-repl
spec:
  ...
  replication:
    enabled: true
    primary:
      podIndex: 0
      automaticFailover: true
      lockStrategy: (ReadOnly | ReadLock)
```

**Comment by harunkucuk5** [comment]
Hey @mmontes11, read-only may be enough but on the other hand if there are some application users with `SUPER` privilege this would cause data loss on the new primary along with the broken replication. Ideally, there should not be any application user with `SUPER` privilege but, unfortunately, when it comes to real-world cases it is not like that in many cases I have seen. I think the operator should provide a reliable auto-failover mechanism regardless of the user privileges. I was unaware that the `FLUSH TABLES WITH READ LOCK ` was already used and caused some issues. I will check the history. But if we implement this and it works without any issues then there should not be any need for the read-only option. Let me check this and get back to you later on

**Comment by mmontes11** [comment]
Hey @harunkucuk5 ! 

I agree, consistency and relibability is probably the most important thing during switchover/failover, let's bring this change back in!

This was introduced in [v0.0.15](https://github.com/mariadb-operator/mariadb-operator/releases/tag/v0.0.15) via this PR:
- https://github.com/mariadb-operator/mariadb-operator/pull/127

I will re-apply it and see how it behaves so we can consider to ship it with `v0.0.24`.

**Comment by mmontes11** [comment]
Here it is the PR, could you PTAL? 🙏🏻 : 
- https://github.com/mariadb-operator/mariadb-operator/pull/310

**Comment by mmontes11** [comment]
Supported by this PR:
- https://github.com/mariadb-operator/mariadb-operator/pull/311
