### ISSUE TITLE
[Feature] Enhanced upgrades tailored for `MariaDB` reliability.

### ISSUE THREAD

**Issue by mariadb-mmontes** [mariadb-operator/mariadb-operator#321]
**Describe the solution you'd like**
We should implement a custom, reliable, MariaDB state aware upgrade mechanism:
- Restart replicas and then master
- Restart one `Pod` at a time making sure it is in sync.

**Describe alternatives you've considered**
Use default `StatefulSet` rolling upgrade strategies, but it doesn't take into account the MariaDB state, which means that a master node could potentially be upgraded first, and therefore also disrupted.

**Additional context**
This will unblock `spec.myCnf` updates:
- https://github.com/mariadb-operator/mariadb-operator/issues/320

**Comment by mariadb-pieterhumphrey** [comment]
Doesn't use K8s stateful set construct.

Also implies feature flagging "upgradable" as a pod level attribute, so you can opt replicas/masters in/out of the upgrade path.
Enables TLS: https://github.com/mariadb-operator/mariadb-operator/issues/137

Reminder:  In Galera, all nodes are masters / all writable.  In async replication, replicas cannot receive writes so they need a different upgrade path.
