### ISSUE TITLE
[Feature] Allow non-pv MariaDB environment

### ISSUE THREAD

**Issue by outductor** [mariadb-operator/mariadb-operator#322]
**Is your feature request related to a problem? Please describe.**

as of 0.24.0, `MariaDB` requires the `volumeClaimTemplate` field. (see https://github.com/mariadb-operator/mariadb-operator/blob/v0.0.24/examples/manifests/mariadb_v1alpha1_mariadb_minimal.yaml)

In some scenarios such as running inside a CI environment or test environment, non-pv MariaDB instance is much easier to handle and can be more flexible.

**Describe the solution you'd like**
`volumeClaimTemplate` to be optional

**Describe alternatives you've considered**

**Environment details**:
- Kubernetes version: [Version number]
- Kubernetes distribution: [Vanilla, EKS, GKE, AKS, Rancher, OpenShift, k3s, KIND...]
- mariadb-operator version: 0.24.0
- Install method: helm
- Install flavor: recommended

**Additional context**

**Comment by mmontes11** [comment]
Hey there @outductor ! Thanks for bringing this up.

I agree, this has a lot of use cases for running in dev and test scenarios, like running inside a CI pipeline where the data durability is not a concern.

As in https://github.com/mariadb-operator/mariadb-operator/issues/323, I suggest we create a flag for this:

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  ephemeralStorage: true
 ```
 The `volumeClaimTemplate` will be optional now, but if neither `spec.volumeClaimTemplate` nor `spec.ephemeralStorage` are set, the validation webhook will return an error. This is to avoid situations where the user probably haven't thought about the storage too much, preventing unwanted situations where the `MariaDB` is running with ephemeral storage in productive environments.
