### ISSUE TITLE
[Feature] add empty password option in MariaDB resource

### ISSUE THREAD

**Issue by outductor** [mariadb-operator/mariadb-operator#323]
**Is your feature request related to a problem? Please describe.**

MariaDB Docker image has an option to make root password empty, however, the current operator spec doesn't support such an environment. (ref. https://hub.docker.com/_/mariadb)

empty password environment can be useful for test and CI use-cases where workloads cannot load secretRefs which is most likely set as environment variables. In this environemnt, passing a static password or even empty password would be useful.

**Describe the solution you'd like**

add empty password option in MariaDB resource

**Describe alternatives you've considered**

**Environment details**:
- Kubernetes version: [Version number]
- Kubernetes distribution: [Vanilla, EKS, GKE, AKS, Rancher, OpenShift, k3s, KIND...]
- mariadb-operator version: 0.24.0
- Install method: helm
- Install flavor: recommended

**Additional context**

**Comment by mmontes11** [comment]
Hey @outductor ! thanks for opening this,

Indeed, this can have a lot of use cases in dev and test scenarios. We could do something like:

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootEmptyPassword: true
 ```
 
 To declare that we want a `MariaDB` empty password. Bear in mind that `MARIADB_ALLOW_EMPTY_ROOT_PASSWORD` must be set, see [docker image](https://hub.docker.com/_/mariadb) docs.
 
 This won't affect the current default behaviour: the operator defaults the root password if `spec.rootPasswordKeyRef` is not provided.
