### ISSUE TITLE
[Feature] Add service account name to MariaDB spec

### ISSUE THREAD

**Issue by hv036** [mariadb-operator/mariadb-operator#333]
**Is your feature request related to a problem? Please describe.**
I believe we should allow users to define their own service accounts. Additionally, in clusters prior to version 1.25 with Pod Security Policies (PSPs) where running as root is restricted, defining a custom service account for MariaDB will be beneficial

**Describe the solution you'd like**
Add `serviceAccountName` in [MariaDBSpec](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/API_REFERENCE.md#mariadbspec)

**Environment details**:
- mariadb-operator version: 0.0.24
- Install method: helm

**Comment by Hoega** [comment]
I think it should be completed now, PR #339 implements a serviceAccountName parameter.

**Comment by mmontes11** [comment]
Supported in the following PR:
- https://github.com/mariadb-operator/mariadb-operator/pull/339
