### ISSUE TITLE
[Feature] S3 backup/restore add subpath location

### ISSUE THREAD

**Issue by brainkiller** [mariadb-operator/mariadb-operator#344]
**Is your feature request related to a problem? Please describe.**
I'm backing up multiple databases to a single bucket. and I'd need an easy way to identify which database each backup is from.
I though of setting either the filename to include the database name or set a different subpath for each database.
A different subpath seems the most efficient.

**Describe the solution you'd like**
Please include a subpath in the backup definition.
Like:
  storage:
    s3:
      bucket: backup-s3
      endpoint: backup-s3:8000
      subpath: mydbname

**Describe alternatives you've considered**
I considered using the database name in the filename but I couldn´t find a way to set the backup filename.

**Environment details**:
- Kubernetes version: 1.28
- Kubernetes distribution: RKE2
- mariadb-operator version: 0.0.24
- Install method: helm

**Comment by mmontes11** [comment]
Hey there @brainkiller ! 

This should be covered by this PR:
- https://github.com/mariadb-operator/mariadb-operator/pull/338

It is almost ready to go
