### ISSUE TITLE
[Feature] Backup to Google Buckets

### ISSUE THREAD

**Issue by klauserber** [mariadb-operator/mariadb-operator#349]
**Is your feature request related to a problem? Please describe.**
I like to backup direct to Google Buckets.

**Describe the solution you'd like**
Best solution would be native support like the new S3 support.

But for the meantime it should be possible to set a ServiceAccount and Annotations in the resulting Job/CronJob. Then it is possible to use gke-gcsfuse (https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver?hl=de).

**Environment details**:
- Kubernetes version: 1.27.8
- Kubernetes distribution: GKE
- mariadb-operator version: 0.0.23
- Install method: helm
- Install flavor: recommended

**Additional context**

**Comment by mmontes11** [comment]
Hey there @klauserber ! 

Definetly I would love to support this natively, not only Google but also Azure buckets. Unfortunately this take some time to properly abstract all the implementation details of each cloud provider.

For the time being, I suggest we support this with the solution you suggested, I've created the following issues:
- https://github.com/mariadb-operator/mariadb-operator/issues/352
- https://github.com/mariadb-operator/mariadb-operator/issues/353

Contributions are welcome! I think this, not only solve the current issue, but will provide a lot of flexibility to our `Backup`/ `Restore` jobs.

**Comment by mmontes11** [comment]
Hey there @klauserber  ! 

This has been addressed. You can now specify a `serviceAccountName` to `Backup` and `Restore` objects and inject metadata to  it by passing the `inheritMetadata` property, which propagates labels and annotations to all the children objects, including the `ServiceAccount` and `Pod` objects. Please take a look at the updated examples:

- https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/mariadb_v1alpha1_backup.yaml

Closing! This will be released in `v0.0.26`. Stay tuned!

**Comment by klauserber** [comment]
Very good! Thank you!

**Comment by nilsthieme** [comment]
Hi @klauserber, were you able to make backups to Google Buckets work this way?

The backup Job's mariadb initcontainer seems to fail after its initial (successful) write to the bucket, as [running chmod isn't permitted](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver#considerations):
> 💾 Exporting env
💾 Writing target file: /backup/0-backup-target.txt
💾 Setting target file permissions
chmod: changing permissions of '/backup/0-backup-target.txt': Operation not permitted

I did not find a way to not run the ["chmod 777"](https://github.com/mariadb-operator/mariadb-operator/blob/v0.0.29/pkg/command/backup.go#L154) here nor any other workaround. @mmontes11 am I missing something?

<details>
<summary>backup.yaml</summary>

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: BACKUP_NAME
  namespace: NAMESPACE
spec:
  inheritMetadata:
    annotations:
      gke-gcsfuse/volumes: 'true'
  logLevel: debug
  mariaDbRef:
    name: CLUSTER_NAME
  serviceAccountName: SA_NAME
  storage:
    volume:
      csi:
        driver: gcsfuse.csi.storage.gke.io
        volumeAttributes:
          bucketName: BUCKET_NAME
          gcsfuseLoggingSeverity: warning
          mountOptions: file-mode=0777,dir-mode=0777
```

</details>

<details>
<summary>live manifest of failed job</summary>

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    gke-gcsfuse/volumes: 'true'
  creationTimestamp: '2024-08-22T12:06:05Z'
  generation: 1
  labels:
    batch.kubernetes.io/controller-uid: 71c50093-5704-4035-841f-0b1c6290bdf2
    batch.kubernetes.io/job-name: BACKUP_NAME
    controller-uid: 71c50093-5704-4035-841f-0b1c6290bdf2
    job-name: BACKUP_NAME
  name: BACKUP_NAME
  namespace: NAMESPACE
  ownerReferences:
    - apiVersion: k8s.mariadb.com/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Backup
      name: BACKUP_NAME
      uid: 10cf4cb1-2bcf-45c2-a04d-c48a4b43b97f
  resourceVersion: '6853935'
  uid: 71c50093-5704-4035-841f-0b1c6290bdf2
spec:
  backoffLimit: 5
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 71c50093-5704-4035-841f-0b1c6290bdf2
  suspend: false
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: 'true'
      creationTimestamp: null
      labels:
        batch.kubernetes.io/controller-uid: 71c50093-5704-4035-841f-0b1c6290bdf2
        batch.kubernetes.io/job-name: BACKUP_NAME
        controller-uid: 71c50093-5704-4035-841f-0b1c6290bdf2
        job-name: BACKUP_NAME
      name: BACKUP_NAME
      namespace: NAMESPACE
    spec:
      affinity: {}
      containers:
        - args:
            - backup
            - '--path'
            - /backup
            - '--target-file-path'
            - /backup/0-backup-target.txt
            - '--max-retention'
            - 720h0m0s
            - '--log-level'
            - debug
          image: >-
            docker-registry3.mariadb.com/mariadb-operator/mariadb-operator:v0.0.29
          imagePullPolicy: IfNotPresent
          name: mariadb-operator
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /backup
              name: backup
      dnsPolicy: ClusterFirst
      initContainers:
        - args:
            - >-
              set -euo pipefail;echo 💾 Exporting env;export
              BACKUP_FILE=backup.$(date -u +'%Y-%m-%dT%H:%M:%SZ').sql;echo 💾
              Writing target file: /backup/0-backup-target.txt;printf
              "${BACKUP_FILE}" > /backup/0-backup-target.txt;echo 💾 **Setting
              target file permissions;chmod 777 /backup/0-backup-target.txt**;echo
              💾 Taking backup: /backup/$(cat
              '/backup/0-backup-target.txt');mariadb-dump
              --user=${MARIADB_OPERATOR_USER}
              --password=${MARIADB_OPERATOR_PASSWORD}
              --host=CLUSTER_NAME.NAMESPACE.svc.cluster.local
              --port=3306 --single-transaction --events --routines
              --all-databases --skip-add-locks --ignore-table=mysql.global_priv
              > /backup/$(cat '/backup/0-backup-target.txt')
          command:
            - bash
            - '-c'
          env:
            - name: MARIADB_OPERATOR_USER
              value: root
            - name: MARIADB_OPERATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: root-password
                  name: SECRET_NAME
          image: docker-registry1.mariadb.com/library/mariadb:10.11.8
          imagePullPolicy: IfNotPresent
          name: mariadb
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /backup
              name: backup
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 999
        runAsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
      serviceAccount: SA_NAME
      serviceAccountName: SA_NAME
      terminationGracePeriodSeconds: 30
      volumes:
        - csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: BUCKET_NAME
              gcsfuseLoggingSeverity: warning
              mountOptions: file-mode=0777,dir-mode=0777
          name: backup
status:
  conditions:
    - lastProbeTime: '2024-08-22T12:09:15Z'
      lastTransitionTime: '2024-08-22T12:09:15Z'
      message: Job has reached the specified backoff limit
      reason: BackoffLimitExceeded
      status: 'True'
      type: Failed
  failed: 1
  ready: 0
  startTime: '2024-08-22T12:06:05Z'
  terminating: 0
  uncountedTerminatedPods: {}
```

</details>

**Environment details:**

Kubernetes version: v1.29.7-gke.1104000
Kubernetes distribution: GKE
mariadb-operator version: 0.0.29
Install method: helm
Install flavor: recommended
