### ISSUE TITLE
The Quickstart instructions don't work..[Bug] 

### ISSUE THREAD

**Issue by jbrinnand** [mariadb-operator/mariadb-operator#367]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

I followed your instructions:

Let's see how mariadb-operator🦭 and Galera play together! First of all, install the following configuration manifests that will be referenced by the CRDs further:

kubectl apply -f examples/manifests/config
Next, you can proceed with the installation of a MariaDB instance with Galera support:

kubectl apply -f examples/manifests/mariadb_v1alpha1_mariadb_galera.yaml

Here is what happened. It looks like there is a CRD that should have been applied prior to these to steps. Where is that CRD?

**error: resource mapping not found for name: "mariadb-galera" namespace: "" from "examples/manifests/mariadb_v1alpha1_mariadb_galera.yaml": no matches for kind "MariaDB" in version "mariadb.mmontes.io/v1alpha1"
ensure CRDs are installed first**

I am not sure what CRD needs to be installed first, and I am not seeing this in your instructions.

Also - will this operator work on arm64?

Thanks for your help.

**Comment by mmontes11** [comment]
Hey there @jbrinnand ! Thanks for reporting 

> error: resource mapping not found for name: "mariadb-galera" namespace: "" from "examples/manifests/mariadb_v1alpha1_mariadb_galera.yaml": no matches for kind "MariaDB" in version "mariadb.mmontes.io/v1alpha1"
ensure CRDs are installed first

The `mariadb-operator` CRDs are not installed in your cluster. How did you installed the operator? You can either install them by installing the helm chart:
- https://github.com/mariadb-operator/mariadb-operator?tab=readme-ov-file#bare-minimum-installation
or alternatively you can install the manifests available in the release page:
- https://github.com/mariadb-operator/mariadb-operator/releases/tag/helm-chart-0.25.0

> Also - will this operator work on arm64?

Yes, it is happily running on my Raspberry pi

**Comment by jbrinnand** [comment]
Hi Martin,

Thanks for your response and the information. The helm installation works
and installs a single instance of MariaDB. I found how to configure
replication and set up 3 replicas. My next question is: how would I
configure a CR to use Galera with a minimum of 3 replicas and have
auto-scaling enabled? I will go through the CRD and try to work out how
that might be accomplished, but aren't there galera directives to be added
to the myCnf section? Where might I find these directives?

Thanks again for your help. It is much appreciated.

John

**Comment by jbrinnand** [comment]
Martin,

Many thanks for the response and the info. It is great! I will try it out.

Best regards,

John

**Comment by jbrinnand** [comment]
Hi Martin,

Well I tried to run the examples as you described.

   - I first installed the operator (*helm install mariadb-operator
   mariadb-operator/mariadb-operator*)
   - I checked to see if the CRDs were created by the operator and they
   were.
   - The operator appeared to be up and running.
   - Next - I tried installing mariadb_galera:  *kubectl apply -f
   examples/manifests/mariadb_galera.yaml*
   - I checked the logs of mariadb-galera-init-xxxxxx pod and the first
   time everything connected okay.  It also created 3 database instances.
   - I next installed maxscale_galera.yaml  (*kubectl apply -f
   examples/manifests/maxscale_galera.yaml*) and it worked - for a while!
   - Then I noticed that I started getting this error every time I tried to
   access the database:: 2024-03-22 23:21:51 30 [Warning] Access denied for
   user 'root'@'localhost' (using password: YES) Note: I haven't changed
   any user names or passwords. Where is the secret password located and
   who is responsible for creating it? I don't see a reference to it and it
   doesn't appear to exist when I use kubectl to look for it.
   - So I tried reinstalling everything in the same sequence. However,
   everytime i perform an installation, I notice that the pod
   mariadb-galera-init-xxxxx pod has the same "Access denied" error which
   repeats constantly then the pod restarts and goes through the same process
   again. FInally, after a number of retries, it exits.  I

I am out of options. The entire examples/manifests directory contents have
changed dramatically and there is no indication of how to make it work. So
- what I did previously does not work and what does work is so flaky that I
can't rely on it at all. Short of clearing my cluster completely, I don't
know what else to do.  Also - none of the Quickstart directions work with
the galera flavored workloads.

There is no direction or inclination of what is actually going wrong or
why.

Any light you can shed on this issue would be greatly appreciated.

Thanks,

John

**Comment by jbrinnand** [comment]
Hi Martin,

The last problem with Access Denied errors is fixed. This problem
occurred because the password changed in the latest version of
mariadb-operator but the older version from a previous deployment was held
in place by the PVs and PVCs. So - when the operator tried to bring up the
mariadb instances, the new password was not used. Instead the password from
the previous deployment was used leading to Access Denied errors.

For me to get the mariadb-operator to successfully install mariadb_galera
or mariadb_galera_maxscale, or any other workload, all previous mariadb
artifacts had to be removed from the cluster. This included: services,
crds, secrets, databases, sqljobs, mariadb instances, etc. Then the steps
you outlined can be taken and the mariadb maxscale pods can be successfully
installed.

It is important to note that the latest manifests are quite different from
existing documentation. So care must be taken when deploying the latest
version of the mariadb operator. Also, the mariadb operator deploys all the
CRDs which are required, so there is no need to deploy CRDs separately.
Finally, all the secrets in the examples/manifests/config directory must be
applied prior to installing the operator or the mariadb instances will not
be created. After these steps are taken, the user can successfully install
the operator and then mariadb_galera, mariadb_galera_maxscele, etc.

Thanks,

John

**Comment by mmontes11** [comment]
Hey @jbrinnand ! 

Thanks for your detailed response.

Yes, `v0.0.27` brought important changes onboard, including some breaking changes. This affects both the CRDs and the examples. When that happens, we communicate that in the release notes:
- https://github.com/mariadb-operator/mariadb-operator/releases/tag/v0.0.27

and we also provide a migration guide:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/UPGRADE_v0.0.26.md

So I guess at this point everything is up and running. Shall we close this issue?

**Comment by jbrinnand** [comment]
Hi Martin,

Yes - we can close this issue.

Many thanks for your help.

Best regards,

John
