### ISSUE TITLE
Pods fail to start - can't get Persistent Volumes

### ISSUE THREAD

**Issue by n7qnm** [mariadb-operator/mariadb-operator#374]
Looks like I'm missing some PVs

Help!

Ran 
      kubectl apply -f examples/manifests/mariadb_v1alpha1_mariadb.yaml

kubectl  get pod
    mariadb-0                                                0/1     Pending   0               7m38s

kuebctl get evevt
9m5s        Warning   FailedScheduling    pod/mariadb-0                                    0/4 nodes are available: persistentvolumeclaim "storage-mariadb-0" bound to non-existent persistentvolume "pvc-2395f2db-c079-4440-a4b9-2dafaeb79452". preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
3m41s       Warning   FailedScheduling    pod/mariadb-0                                    0/4 nodes are available: persistentvolumeclaim "storage-mariadb-0" bound to non-existent persistentvolume "pvc-2395f2db-c079-4440-a4b9-2dafaeb79452". preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.

**Comment by mmontes11** [comment]
Hey there @n7qnm ! 

Seems like you are having scheduling problems in your cluster:
```bash
persistentvolumeclaim "storage-mariadb-0" bound to non-existent persistentvolume 
```
If a `storageClass` is not provided in the `spec.volumeClaimTemplate` then the default one is used by Kubernetes. Make sure you have a default `StorageClass` or explicitly provide one.
