### ISSUE TITLE
[Feature] Add a "revisionHistoryLimit" to Certificate resource

### ISSUE THREAD

**Issue by kettil** [mariadb-operator/mariadb-operator#380]
**Describe the solution you'd like**

Cert-Manager does not normally delete CertificateRequests so that they accumulate.
It would be nice if the template [webhook-certificate.yaml](https://github.com/mariadb-operator/mariadb-operator/blob/main/deploy/charts/mariadb-operator/templates/webhook-certificate.yaml) could be extended so that the [Certificate](https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSpec) resource has the optional setting `revisionHistoryLimit`, so that old CertificateRequests are automatically deleted.

Exemplary extension:

```diff
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "mariadb-operator.fullname" . }}-webhook-cert
  # ...
spec:
  commonName: {{ include "mariadb-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
  # ...

+ {{- if .Values.webhook.cert.certManager.revisionHistoryLimit -}}
+ revisionHistoryLimit:  {{ .Values.webhook.cert.certManager.revisionHistoryLimit }}
+ {{- end }}

  # ...
```

**Comment by mmontes11** [comment]
Hey @kettil ! Thanks for suggesting this.

Totally agree, without `revisionHistoryLimit` and running `cert-manager` for a while it is likely that the cluster ends up with a flooding of `CertificateRequests`.

Your examples looks good, could you raise a PR with it?

Thanks for your contribution! 🦭 🙏🏻
