### ISSUE TITLE
[Bug] Operator may not trigger galera recovery if pods are restarting

### ISSUE THREAD

**Issue by djakobczak1** [mariadb-operator/mariadb-operator#424]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

When galera pod keeps restarting due to e.g. failure during SST it firstly joins the cluster, which increases `wsrep_cluster_size`.
Due to that behavior `recovery.MinClusterSize` may not be respected correctly, because in galera reconcile loop there is a waiter that monitors `wsrep_cluster_size` to give some time (`recovery.ClusterHealthyTimeout`) for a cluster to recover on its own.

Let's imagine that we have 3-node cluster and we set `MinClusterSize` to 50%.
1. first pod enters CrashLoopBack 
    - operator checks  cluster size, which is above `MinClusterSize`
2 one of 2 remaining healthy pods is killed
3. operator is notified due to generated event
    - operator triggers  `pollUntilHealthyWithTimeout`
    - wsrep_cluster_size is 1 at this moment
4. pod starts within `ClusterHealthyTimeout` and can communicate with the cluster, so it increases `wsrep_cluster_size` to 2
5. operator sees that `wsrep_cluster_size` is now above `MinClusterSize` so it finishes reconciliation
6. started pod fails during e.g. SST and restarts, now operator will not notice that

**Expected behaviour**

Operator triggers recovery procedure if number of members of Primary Component is below `MinClusterSize`

**Steps to reproduce the bug**

1. Force 2 out of 3 pods to enter CrashLoopBack with e.g.
```
k exec <pod> -- sh -c 'echo 1 > /var/lib/mysql/wsrep_sst.pid'
```
2. Delete pods to force them restarting

**Debug information**

Operator logs when it decides that cluster has minimum number of replicas, because restarted replica temporary joined the cluster.
```bash
{"level":"debug","ts":1709299832.2333553,"logger":"pod-galera","msg":"Reconciling Pod in non Ready state","controller":"pod","controllerGroup":"","controllerKind":"Pod","Pod":{"name":"mariadb-2","namespace":"default"},"namespace":"default","name":"mariadb-2","reconcileID":"c0e85d6f-353a-42d3-b71f-600f90d3f2ac","pod":"mariadb-2"}
{"level":"info","ts":1709299832.2483318,"logger":"galera.health","msg":"StatefulSet ready replicas","controller":"statefulset","controllerGroup":"apps","controllerKind":"StatefulSet","StatefulSet":{"name":"mariadb","namespace":"default"},"namespace":"default","name":"mariadb","reconcileID":"6f12186f-2609-4694-9c74-5364659bc233","replicas":1}
{"level":"info","ts":1709299832.2551696,"logger":"galera.health","msg":"Galera cluster size","controller":"statefulset","controllerGroup":"apps","controllerKind":"StatefulSet","StatefulSet":{"name":"mariadb","namespace":"default"},"namespace":"default","name":"mariadb","reconcileID":"6f12186f-2609-4694-9c74-5364659bc233","size":1,"has-min-size":false}
{"level":"info","ts":1709299833.2479248,"logger":"galera.health","msg":"StatefulSet ready replicas","controller":"statefulset","controllerGroup":"apps","controllerKind":"StatefulSet","StatefulSet":{"name":"mariadb","namespace":"default"},"namespace":"default","name":"mariadb","reconcileID":"6f12186f-2609-4694-9c74-5364659bc233","replicas":1}
{"level":"info","ts":1709299833.2548144,"logger":"galera.health","msg":"Galera cluster size","controller":"statefulset","controllerGroup":"apps","controllerKind":"StatefulSet","StatefulSet":{"name":"mariadb","namespace":"default"},"namespace":"default","name":"mariadb","reconcileID":"6f12186f-2609-4694-9c74-5364659bc233","size":1,"has-min-size":false}
{"level":"info","ts":1709299834.250786,"logger":"galera.health","msg":"StatefulSet ready replicas","controller":"statefulset","controllerGroup":"apps","controllerKind":"StatefulSet","StatefulSet":{"name":"mariadb","namespace":"default"},"namespace":"default","name":"mariadb","reconcileID":"6f12186f-2609-4694-9c74-5364659bc233","replicas":1}
{"level":"info","ts":1709299834.2562437,"logger":"galera.health","msg":"Galera cluster size","controller":"statefulset","controllerGroup":"apps","controllerKind":"StatefulSet","StatefulSet":{"name":"mariadb","namespace":"default"},"namespace":"default","name":"mariadb","reconcileID":"6f12186f-2609-4694-9c74-5364659bc233","size":1,"has-min-size":false}
{"level":"info","ts":1709299835.2475395,"logger":"galera.health","msg":"StatefulSet ready replicas","controller":"statefulset","controllerGroup":"apps","controllerKind":"StatefulSet","StatefulSet":{"name":"mariadb","namespace":"default"},"namespace":"default","name":"mariadb","reconcileID":"6f12186f-2609-4694-9c74-5364659bc233","replicas":1}
{"level":"info","ts":1709299835.2517285,"logger":"galera.health","msg":"Galera cluster size","controller":"statefulset","controllerGroup":"apps","controllerKind":"StatefulSet","StatefulSet":{"name":"mariadb","namespace":"default"},"namespace":"default","name":"mariadb","reconcileID":"6f12186f-2609-4694-9c74-5364659bc233","size":2,"has-min-size":true}
{"level":"info","ts":1709299835.2525787,"logger":"galera.health","msg":"Checking Galera cluster health","controller":"statefulset","controllerGroup":"apps","controllerKind":"StatefulSet","StatefulSet":{"name":"mariadb","namespace":"default"},"namespace":"default","name":"mariadb","reconcileID":"ae72c862-0276-45e8-a36f-9a9b26fde2b1"}
{"level":"info","ts":1709299835.252841,"logger":"galera.health","msg":"StatefulSet ready replicas","controller":"statefulset","controllerGroup":"apps","controllerKind":"StatefulSet","StatefulSet":{"name":"mariadb","namespace":"default"},"namespace":"default","name":"mariadb","reconcileID":"ae72c862-0276-45e8-a36f-9a9b26fde2b1","replicas":1}
{"level":"info","ts":1709299835.2553465,"logger":"galera.health","msg":"Galera cluster size","controller":"statefulset","controllerGroup":"apps","controllerKind":"StatefulSet","StatefulSet":{"name":"mariadb","namespace":"default"},"namespace":"default","name":"mariadb","reconcileID":"ae72c862-0276-45e8-a36f-9a9b26fde2b1","size":2,"has-min-size":true}
```

Mariadb pods status:
```
❯ k get po -l app.kubernetes.io/instance=mariadb
NAME        READY   STATUS             RESTARTS        AGE
mariadb-0   2/2     Running            0               12m
mariadb-1   1/2     CrashLoopBackOff   5 (107s ago)    6m5s
mariadb-2   1/2     CrashLoopBackOff   5 (2m25s ago)   6m50s
```

MariaDB CR galera recovery options:
``` yaml
      recovery:
        clusterBootstrapTimeout: 10m0s
        clusterHealthyTimeout: 1m0s
        enabled: true
        minClusterSize: 50%
        podRecoveryTimeout: 5m0s
        podSyncTimeout: 5m0s

```

**Environment details**:
- Kubernetes version: v1.28.0
- Kubernetes distribution: KIND
- mariadb-operator version: 0.26.0
- Install method: helm
- Install flavor: custom

**Comment by mmontes11** [comment]
Hey @djakobczak1 ! Sorry for late response.

Very accurate issue report! I've managed to reproduce, will get back to you with a suggestion soon. 👍🏻

**Comment by mmontes11** [comment]
@djakobczak1 I think now I understand the root cause of the problem and have a suggestion to solve it.

> 5. operator sees that `wsrep_cluster_size` is now above `MinClusterSize` so it finishes reconciliation
> 6. started pod fails during e.g. SST and restarts, now operator will not notice that

Indeed, once the cluster reaches healthy state the reconciliation stops and the operator misses that the `wsrep_cluster_size` goes below the `MinClusterSize`. 

__Why?__

Currently the [controller responsible for this ](https://github.com/mariadb-operator/mariadb-operator/blob/main/controller/statefulset_galera_controller.go) subscribes to the events of the `StatefulSet`, basically whenever something changes in the `StatefulSet` a reconciliation is triggered to check whether the cluster is healthy and it sets the `GaleraReady` accordingly so the other [controller performs the recovery.](https://github.com/mariadb-operator/mariadb-operator/blob/main/pkg/controller/galera/recovery.go). 

The problem is that there are situations like this one (but probably more) where the `Pods` reach a `CrashLoopBackOff` state, so nothing in the `StatefulSet` is changed, and therefore no reconciliations are enqueued. 

__How to solve it?__

I've managed to trigger the recovery in the scenario you reported by requeuing reconciliations every 10s even if the cluster is healthy. I suggest we introduce a `clusterMonitorInterval`, by default set to 10s:

```yaml
spec:
  galera:
    recovery:
       clusterMonitorInterval: 10s
```

This way we will allow the user to configure the interval at which the cluster is monitored so we make sure we don't miss any event!

As an alternative, I thought about subscribing to the `Pods` state, but there might be situations where no reconciliations are trigered for the `Pods` either, like advanced `CrashLoopBackoff` state.

What do you think?

**Comment by djakobczak1** [comment]
Thank you for detailed response.
Suggested solution with configurable `clusterMonitorInterval` sounds good to me from user perspective.

**Comment by mmontes11** [comment]
Great @djakobczak1 ! I will raise a PR soon for supporting this.
