### ISSUE TITLE
[Feature] Recover from abrupt node shutdown during SST

### ISSUE THREAD

**Issue by djakobczak1** [mariadb-operator/mariadb-operator#425]
**Is your feature request related to a problem? Please describe.**

When one of the nodes with galera server is restarted abruptly during SST, pod may enter crashLoopBack due to stale  `sst_in_progress`/`wsrep_sst.pid` files.

```
WSREP_SST: [INFO] Stale sst_in_progress file: /var/lib/mysql/sst_in_progress (20240301 10:25:49.732)
WSREP_SST: [INFO] previous SST is not completed, waiting for it to exit (20240301 10:25:49.822)
2024-03-01 10:25:50 0 [Note] WSREP: (11659a97-92de, 'tcp://0.0.0.0:4567') turning message relay requesting off
WSREP_SST: [INFO] previous SST is not completed, waiting for it to exit (20240301 10:25:50.840)
WSREP_SST: [INFO] previous SST is not completed, waiting for it to exit (20240301 10:25:51.858)
WSREP_SST: [INFO] previous SST is not completed, waiting for it to exit (20240301 10:25:52.874)
WSREP_SST: [INFO] previous SST is not completed, waiting for it to exit (20240301 10:25:53.890)
WSREP_SST: [INFO] previous SST is not completed, waiting for it to exit (20240301 10:25:54.909)
WSREP_SST: [INFO] previous SST is not completed, waiting for it to exit (20240301 10:25:55.927)
WSREP_SST: [INFO] previous SST is not completed, waiting for it to exit (20240301 10:25:56.943)
WSREP_SST: [INFO] previous SST is not completed, waiting for it to exit (20240301 10:25:57.962)
WSREP_SST: [INFO] previous SST is not completed, waiting for it to exit (20240301 10:25:58.980)
WSREP_SST: [ERROR] previous SST script still running. (20240301 10:25:58.987)
2024-03-01 10:25:58 0 [ERROR] WSREP: Failed to read 'ready <addr>' from: wsrep_sst_mariabackup --role 'joiner' --address '10.244.1.20' --datadir '/var/lib/mysql/' --parent 1 --progress 0
```

From my understanding currently MariaDB Operator will not trigger recovery procedure if number of cluster member is higher than `MinClusterSize` of total number of replicas.
However, I think operator should also have mechanism to try to recover from above described unrecoverable state, because state with one or more servers in failed status results in:
* makes it more likely to trigger full recovery procedure when another pod will enter error state
* decreased read cluster performance

**Describe the solution you'd like**

Operator detects unrecoverable (i.e. pod restart triggered by liveness probe is not enough) state and recovers failed pod(s).

**Describe alternatives you've considered**

Operator waits for more pods to fail and then triggers recovery procedure.

**Environment details**:
- Kubernetes version: 1.28.0
- Kubernetes distribution: KIND
- mariadb-operator version: 0.26.0
- Install method: helm
- Install flavor: custom

**Additional context**

Issue can be reproduced for tests with
```
k exec <pod> -- sh -c 'echo 1 > /var/lib/mysql/wsrep_sst.pid'
k delete po <pod>
```

**Comment by mmontes11** [comment]
Hey @djakobczak1 ! Thanks for suggesting this feature.

I think we could improve the management of  __pending SSTs__ in the following ways:

### Prevention

We could check whether the `/var/lib/mysql/sst_in_progress` is present in the agent side and return a 200 OK in the liveness probe. This way the `Pod` won't be restarted by Kubernetes when a SST is pending, potentially helping with the SST completion. 

### Detection

Expose an HTTP endpoint in the agent that would return a 200 OK when `/var/lib/mysql/sst_in_progress` is present. This way we can precisely know from the operator side if an SST is pending in every `Pod`. 

### Recovery

We could attempt to recovery the `Pods` with a pending SST in the following situation:
- `wsrep_cluster_size` is greater than or equal than the `MinClusterSize`: 
- `wsrep_cluster_size` is less than the total number of expected `Pods` 

To determine when a pending SST is in a unrecoverable state, we could introduce the following field:
```yaml
spec:
  galera:
    recovery:
       podSSTTimeout: 3m
```
The operator will calling the new agent endpoint to determine whether an SST is in progress and it will track its duration in a status field:

```yaml
status:
   pendingSSTStatus:
       - pod: mariadb-galera-1
         startTime: "2024-03-11T15:15:47Z" 
```
When an SST reaches the timeout in certain `Pod`, the operator will:
- Delete the `/var/lib/mysql/sst_in_progress` file in that `Pod` by calling another agent endpoint
- Restart the `Pod`
- Emit an `Event` and log it in info level to provide the user visibility for troubleshooting the issue on their end.

What do you think?

**Comment by mmontes11** [comment]
@djakobczak1 we are planning to implement this in the current release. Your input about https://github.com/mariadb-operator/mariadb-operator/issues/425#issuecomment-1988863427 would be helpful!

**Comment by comminutus** [comment]
This is happening to me on one of my clusters.  Galera isn't triggering a recovery.  How can I manually recover from this until this feature is implemented?

**Comment by mmontes11** [comment]
@comminutus Manually deleting `/var/lib/mysql/sst_in_progress` in the `Pod` that is stucked performing the SST

**Comment by comminutus** [comment]
@mmontes11 I tried that but when the pod restarts it comes back.
