### ISSUE TITLE
[Bug] migration script doesn't update tolerations key 

### ISSUE THREAD

**Issue by tsgit** [mariadb-operator/mariadb-operator#431]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

the update script from 0.0.25 to 0.0.26 does not correct the old namespace for tolerations in the mariadb galera deployment.

The previous example had

https://github.com/mariadb-operator/mariadb-operator/blob/v0.0.25/examples/manifests/mariadb_v1alpha1_mariadb_galera_full.yaml#L100-L101

```  
tolerations:
    - key: "mariadb.mmontes.io/ha"
```

It should be
https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/mariadb_galera_full.yaml#L107-L108

```  
tolerations:
    - key: "k8s.mariadb.com/ha"
```

but the migration script does not make that adjustment.

**Expected behaviour**

the migrations script should update the toleration key

**Steps to reproduce the bug**

1. use mariadb-galera manifest from v0.0.25
2. apply migration script
3. check the tolerations key

**Debug information**
- Related object events:
```bash
kubectl get events --field-selector involvedObject.name=<mariadb-resource-name>
kubectl get events --field-selector involvedObject.name=<backup-resource-name>
kubectl get events --field-selector involvedObject.name=<restore-resource-name>
```
- `mariadb-operator` logs. Set the `--log-level` to `debug` if needed.

**Environment details**:
- Kubernetes version: [Version number]
- Kubernetes distribution: [Vanilla, EKS, GKE, AKS, Rancher, OpenShift, k3s, KIND...]
- mariadb-operator version: [Version number]
- Install method: [helm, OLM, or static manifests]
- Install flavor: [minimal, recommended, or custom]

**Additional context**

**Comment by mmontes11** [comment]
Hey there @tsgit! Thanks for reporting.

Toleration key values are arbitraty values which don't have really a semantic value, they are opaque to Kubernetes. In order words, they are just values provided as part of our [examples](https://github.com/mariadb-operator/mariadb-operator/blob/v0.0.25/examples/manifests/mariadb_v1alpha1_mariadb_galera_full.yaml#L100-L101).

The only important thing is that you align the value of these keys with the taints of your Nodes, but managing Nodes is out of the scope of this operator.

Closing!
