### ISSUE TITLE
Add N7QNM to the Adopters list

### ISSUE THREAD

**Issue by n7qnm** [mariadb-operator/mariadb-operator#440]
Please add N7QNM to the adopters list - I have an LLC, Jackson Holdings, but prefer to just use my Amateur Radio Callsign, N7QNM.
I have over 10 years of weather data stored in MariaDB (and MySQL before the Sun/Oracle acquisition) that's used by several farmers in the Columbia River basin in Washington State.

I contribute my weather data to NOAA/Citizen's Weather Observer Program and Washington State University's AgWeatherNet.  

I also have over 25 years of Amateur Radio logs and several years of Home Automation (Home Assistant) data stored in MariaDB.

I'm consolidating 3 different databases, one on Windows, 2 on Linux into one Galera Database running in a 3-node kubernetes cluster running inside a 4 Node Proxmox virtual environment.

In my "day job" I'm a Solutions Architect for Quest Software, specializing in database-adjacent products, including SharePlex (Data Movement), Foglight (Database Monitoring) and the TOAD family (database management and SQL Development).

**Comment by mmontes11** [comment]
Hey @n7qnm! What an impressive career, thanks for adopting `mariadb-operator` 🦭 

Could you please open a PR and add you/your project/your company to be [ADOPTERS list](https://github.com/mariadb-operator/mariadb-operator/blob/main/ADOPTERS.md)?

Thanks 🙏🏻
