### ISSUE TITLE
webhook - Address is not allowed

### ISSUE THREAD

**Issue by tirelibirefe** [mariadb-operator/mariadb-operator#49]
```
$ kubectl apply -f config/samples/mariadb_v1alpha1_mariadb.yaml

Error from server (InternalError): error when creating "config/samples/mariadb_v1alpha1_mariadb.yaml": Internal error occurred: failed calling webhook "vmariadb.kb.io": failed to call webhook: Post "https://mariadb-operator-webhook.mariadb-operator.svc:443/validate-mariadb-mmontes-io-v1alpha1-mariadb?timeout=10s": Address is not allowed
```

**Comment by mmontes11** [comment]
Thanks for reporting, it seems like it's a webhook misconfiguration, could you provide the following:
- Kubernetes/Openshift version
- Installation mode: helm chart or mariadb-operator-helm and its version
- MariaDB operator version

Thanks, will look into it when I have the details.

**Comment by RegisHubelia** [comment]
Okay - so installing the controller in kube-system seems like it fixes it.  I guess it has something to do with network policies on rke2 when project isolation is enabled in Rancher...  Just a guess..

**Comment by mmontes11** [comment]
Thanks for your feedback @RegisHubelia ! 

I'm now familiar with RKE2, but it seems like they configure `NetworkPolicies` by default:
- https://docs.rke2.io/security/pod_security_policies

Could you confirm that you have `NetworkPolicies` in the namespace where you initially have issues? It would be ideal if you could share them here.

If that was the case, we could do like [cert-manager ](https://github.com/cert-manager/cert-manager) and create a `NetworkPolicy` inside of the helm chart to allow traffic to the webhook, something like this:
- https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/templates/networkpolicy-webhooks.yaml

**Comment by RegisHubelia** [comment]
That would make sense.  I'll try this again and report back.  Sorry the delay.

**Comment by mmontes11** [comment]
> it's probably more network-policies related

I'm betting the same, drop a comment here when you find the time to debug 👍🏻

**Comment by ox1depl** [comment]
Hi. i have similar issue, when try deploy with gitlab-ci but i`ve got `context deadline exceeded` at the end, its related ? 

k8s version: 1.26.6
k8s provisioner: kOps
Operator version: v0.18.0

`
Error from server (InternalError): error when creating "extras/mariadb.yaml": Internal error occurred: failed calling webhook "mmariadb.kb.io": failed to call webhook: Post "[https://mariadb-operator-webhook.platform.svc:443/mutate-mariadb-mmontes-io-v1alpha1-mariadb?timeout=10s](https://mariadb-operator-webhook.platform.svc/mutate-mariadb-mmontes-io-v1alpha1-mariadb?timeout=10s)": context deadline exceeded
`

But, when I manualy apply the same manifest with kubectl apply -f it works... strange.

**Comment by ox1depl** [comment]
In fact, you can't see it on the cluster, but right after the operator deployment, the manifest is deployed and probably the webhook pod is not ready yet, 
I added a simple sleep to check it and it is indeed as you say.
thank you ;) And forgive me for being off topic, the error was very similar.

**Comment by mmontes11** [comment]
@ox1depl no worries, here to help

@RegisHubelia is this still an issue for you? if not, we can close
