### ISSUE TITLE
[Bug] Cannot create Galera init job with partially defined probe

### ISSUE THREAD

**Issue by djakobczak1** [mariadb-operator/mariadb-operator#516]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

It is not possible to create Galera MariaDB CR with partially defined liveness probe (probably readiness probe as well).

**Expected behaviour**

It is possible to create MariaDB CR with customized only selected probe properties, which can be achieved with removal of user custom probes from init job container.

**Steps to reproduce the bug**

When user only partially overrides liveness probe in MariaDB CR (with Galera enabled), e.g.
```
kind: MariaDB
...
spec:
   livenessProbe:
     periodSeconds: 15
...
```

Batch controller cannot create init job due to following error:
```
2024-03-27T10:26:59.609+0100	ERROR	Reconciler error	{"controller": "mariadb", "controllerGroup": "k8s.mariadb.com", "controllerKind": "MariaDB", "MariaDB": {"name":"mariadb-galera","namespace":"default"}, "namespace": "default", "name": "mariadb-galera", "reconcileID": "1d6137a3-34b7-4e14-ab28-d43778b282f2", "error": "error reconciling Init: 1 error occurred:\n\t* Job.batch \"mariadb-galera-init\" is invalid: spec.template.spec.containers[0].livenessProbe: Required value: must specify a handler type\n\n"
```

It happens because init job is created with raw liveness probe passed from user and in result in provided example container with following liveness probe will be part of init job:
```
v1.Probe {
ProbeHandler: k8s.io/api/core/v1.ProbeHandler {
  Exec: *k8s.io/api/core/v1.ExecAction nil,
  HTTPGet: *k8s.io/api/core/v1.HTTPGetAction nil,
  TCPSocket: *k8s.io/api/core/v1.TCPSocketAction nil,
  GRPC: *k8s.io/api/core/v1.GRPCAction nil},
InitialDelaySeconds: 0,
TimeoutSeconds: 0,
PeriodSeconds: 15,
SuccessThreshold: 0,
FailureThreshold: 0,
TerminationGracePeriodSeconds: *int64 nil
}
```
If user provides probe with ProbeHandler then this issue will not appear.

**Comment by mmontes11** [comment]
Hey there @djakobczak1 ! Thanks for reporting.

This has been already reported by our community here:
- https://github.com/mariadb-operator/mariadb-operator/issues/449

I already have a candidate PR:
- https://github.com/mariadb-operator/mariadb-operator/pull/509

It will be shipped with `v0.0.28`.

**Comment by djakobczak1** [comment]
From [ticket](https://github.com/mariadb-operator/mariadb-operator/issues/449) description I did not realize that it covers this issue as well, but from PR I can see that it should fix it. Thanks

**Comment by mmontes11** [comment]
Yes, it was something I found along the way, I will update the ticket in regards to the Galera init Job.

As you correctly pointed out, the problem was setting the probe provided by the user to the MariaDB container.
