### ISSUE TITLE
[Bug] ArgoCD installation fails using Helm

### ISSUE THREAD

**Issue by plsnotracking** [mariadb-operator/mariadb-operator#522]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

1. Using the following helm chart to install `mariadb-operator` - https://artifacthub.io/packages/helm/mariadb-operator/mariadb-operator
2. Install unsuccessful
3. No special config provided.

**Expected behaviour**

To have `mariadb-operator` deployed using Helm + ArgoCD

**Steps to reproduce the bug**

1. ...
4. ...
5. ...

**Debug information**
- Related object events:
```bash
kubectl get events --field-selector involvedObject.name=<mariadb-resource-name>
❯ kubectl get events --field-selector involvedObject.name=mariadb-operator -n mariadb-operator
LAST SEEN   TYPE     REASON              OBJECT                        MESSAGE
11m         Normal   ScalingReplicaSet   deployment/mariadb-operator   Scaled up replica set mariadb-operator-dc56594f5 to 1
```
- `mariadb-operator` logs. Set the `--log-level` to `debug
 
```bash
{"level":"error","ts":1711691123.5800261,"logger":"controller-runtime.source.EventHandler","msg":"if kind is a CRD, it should be installed before calling Start","kind":"MariaDB.k8s.mariadb.com","error":"no matches for kind \"MariaDB\" in version \"k8s.mariadb.com/v1alpha1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/source/kind.go:63\nk8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2\n\t/go/pkg/mod/k8s.io/apimachinery@v0.28.1/pkg/util/wait/loop.go:73\nk8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.28.1/pkg/util/wait/loop.go:74\nk8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel\n\t/go/pkg/mod/k8s.io/apimachinery@v0.28.1/pkg/util/wait/poll.go:33\nsigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/source/kind.go:56"}
{"level":"error","ts":1711691133.5787992,"logger":"controller-runtime.source.EventHandler","msg":"if kind is a CRD, it should be installed before calling Start","kind":"MariaDB.k8s.mariadb.com","error":"no matches for kind \"MariaDB\" in version \"k8s.mariadb.com/v1alpha1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/source/kind.go:63\nk8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2\n\t/go/pkg/mod/k8s.io/apimachinery@v0.28.1/pkg/util/wait/loop.go:73\nk8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.28.1/pkg/util/wait/loop.go:74\nk8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel\n\t/go/pkg/mod/k8s.io/apimachinery@v0.28.1/pkg/util/wait/poll.go:33\nsigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/source/kind.go:56"}
{"level":"error","ts":1711691143.580054,"logger":"controller-runtime.source.EventHandler","msg":"if kind is a CRD, it should be installed before calling Start","kind":"MariaDB.k8s.mariadb.com","error":"no matches for kind \"MariaDB\" in version \"k8s.mariadb.com/v1alpha1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/source/kind.go:63\nk8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2\n\t/go/pkg/mod/k8s.io/apimachinery@v0.28.1/pkg/util/wait/loop.go:73\nk8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.28.1/pkg/util/wait/loop.go:74\nk8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel\n\t/go/pkg/mod/k8s.io/apimachinery@v0.28.1/pkg/util/wait/poll.go:33\nsigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/source/kind.go:56"}
```

Keeps looking for `MariaDB.k8s.mariadb.com`

**Environment details**:
- Kubernetes version:
```
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.7+k3s1
```
- Kubernetes distribution: k3s
- mariadb-operator version: 0.27.0
- Install method: helm
- Install flavor: recommended

**Additional context**

**Comment by mmontes11** [comment]
Hey there @plsnotracking ! Thanks for reporting.

Unfortunately I am not an ArgoCD user, I normally use Flux for GitOps related stuff, so probably I won't be able to help if the issue is related to ArgoCD.

For some reason, ArgoCD is not installing the CRDs, which are located in the `crds` folder:
https://github.com/mariadb-operator/mariadb-operator/tree/main/deploy/charts/mariadb-operator/crds
This is something helm expects:
https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you

The good news is that there is many people using ArgoCD in the community, please refer to this issues:
https://github.com/mariadb-operator/mariadb-operator/issues?q=is%3Aissue+argocd

**Comment by melledouwsma** [comment]
ArgoCD uses client-side apply by default and fails to apply the CRD because the `kubectl.kubernetes.io/last-applied-configuration` will be too big. You'll find something like this as error in ArgoCD when syncing your application:

```
one or more objects failed to apply, reason: CustomResourceDefinition.apiextensions.k8s.io "mariadbs.k8s.mariadb.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

There are two possible solutions: use either the `Replace=true` or the `ServerSideApply=true` option. You can read more on those options in the documentation:
* [Replace Resource Instead Of Applying Changes](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#replace-resource-instead-of-applying-changes)
* [Server-Side Apply](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#server-side-apply)

For example, a ArgoCD application using the Helm chart will look like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: mariadb-operator
    repoURL: https://mariadb-operator.github.io/mariadb-operator
    targetRevision: 0.27.0
    helm:
      releaseName: mariadb-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mariadb-operator
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Replace=true
```

**Comment by mmontes11** [comment]
Thanks a lot @melledouwsma ! That makes total sense!

I've faced this problem locally with `kubectl` as well, that's why I had to add the `--server-side=true` here:
https://github.com/mariadb-operator/mariadb-operator/blob/7169eb3de4db9143b53a465bce7cd8cf013a3b3e/make/deploy.mk#L139

**Comment by plsnotracking** [comment]
@melledouwsma thanks for the insight, I will try it tonight and get back to you, appreciate the detailed explanation.

@mmontes11 would it make sense to split this the `CRD` into smaller chunks. I'm just guessing, haven't checked to see how complex the CRD actually is. Just wondering, appreciate the work.

**Comment by plsnotracking** [comment]
Sorry for the delay, this seems to have done the trick, really appreciate the feedback, will close it out.
