### ISSUE TITLE
[Bug] can't run 0.0.26 migration script

### ISSUE THREAD

**Issue by evanrich** [mariadb-operator/mariadb-operator#527]
**Documentation**
- [X] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
Downloaded the 0.0.26 migration script, and did the following steps:

1. kubectl get -n mariadb mariadbs.mariadb.mmontes.io mariadb -o yaml > mariadb-mariadb.yaml
2. ran migration script:
```
/migrate_v0.0.26.sh mariadb-mariadb.yaml
```

3. got error
```
yq is already installed. Using the current installation: /usr/bin/yq
yq (https://github.com/mikefarah/yq/) version 4.16.2
Migrating MariaDB fields...
Creating status patch...
Error: Parsing expression: Lexer error: could not match text starting at 1:6 failing at 1:8.
        unmatched text: "pi" 
```
**Expected behaviour**
It works

**Debug information**
- Related object events:
```bash
kubectl get events --field-selector involvedObject.name=<mariadb-resource-name>
kubectl get events --field-selector involvedObject.name=<backup-resource-name>
kubectl get events --field-selector involvedObject.name=<restore-resource-name>
```
- `mariadb-operator` logs. Set the `--log-level` to `debug` if needed.

**Environment details**:
- Kubernetes version: 1.29.3
- Kubernetes distribution: [Vanilla
- mariadb-operator version: [0.0.25]
- Install method: [helm/argocd]
- Install flavor: [recommended?]

**Comment by evanrich** [comment]
Update: i noticed that I have yq 4.16.2, and this script uses 4.42.1.  I uninstalled my YQ, and ran the script again, and it worked. Might want to update the script to error out and/or force the install, as it seemed to be just happy with my older version, yet wouldn't work.

**Comment by mmontes11** [comment]
Thanks for the update @evanrich ! Great to hear that you manage to run the migration.

I will see if there is any way to effectively parse the `yq --version` in bash an `exit 1` with an explanatory message in that case.
