### ISSUE TITLE
[Bug] MariaDB Galera Service constantly refreshing NodePort port number

### ISSUE THREAD

**Issue by luohaha3123** [mariadb-operator/mariadb-operator#541]
**Describe the bug**
I encountered an issue with the MariaDB Galera Service where the NodePort assigned to the service keeps refreshing the port number. This behavior is causing inconsistency and disruption in accessing the MariaDB Galera cluster.

![image](https://github.com/mariadb-operator/mariadb-operator/assets/70438293/97137322-e172-4b8a-9df9-c328ceaadf37)

after seconds...
![image](https://github.com/mariadb-operator/mariadb-operator/assets/70438293/440e846f-a09f-41d5-887c-6394730ac2fc)
<!--

```

**Expected behaviour**
<!--A concise description of what you expected to happen.-->

**Steps to reproduce the bug**
<!--Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.-->

1. Create a galera cluster
2. kubectl get svc


**Environment details**:
- Kubernetes version: v1.17.2
- mariadb-operator version: 0.0.27
- Install method: helm
- Install flavor: custom

**Additional context**
<!--Add any other context  here.-->

**Comment by mmontes11** [comment]
Hey @luohaha3123 ! Thanks for reporting

Unfortunately I couldn't reproduce, could you provide your `MariaDB` object? I'm guessing that your spec is clashing with the operator behaviour.

**Comment by luohaha3123** [comment]
@mmontes11 In the service reconcile process, when the service is configured to use the NodePort type, Kubernetes automatically assigns a port. However, during the reconcile operation by the mariadb-operator, it compares the service configuration with the default configuration and updates the service if they are different. This behavior leads to a constantly changing NodePort port.

https://github.com/mariadb-operator/mariadb-operator/blob/main/pkg/controller/service/controller.go
![bug1](https://github.com/mariadb-operator/mariadb-operator/assets/70438293/1fc53374-fd9d-4489-8ce7-b98eca879ba6)

I think the continuous refresh of the NodePort port is caused by a specific assignment in this code.

**Comment by mmontes11** [comment]
@luohaha3123 good catch, you get it right! 
 
 The same happened with the annotations, as there are some `Services` that are annotated externally, so we need to avoid overriding them if they are already set.
 
```go
	patch := client.MergeFrom(existingSvc.DeepCopy())
	if existingSvc.Spec.Ports == nil {
		existingSvc.Spec.Ports = desiredSvc.Spec.Ports
	}
```

But the code above will set the desired ports only once, something not desirable, as we want the user to be able to change the port but avoid overriding the `nodePort`, as it is set by Kubernetes. We will need to build a more elaborate function for merging the ports.
