### ISSUE TITLE
[Bug] mariadb--metrics  does not follow affinity

### ISSUE THREAD

**Issue by cyford** [mariadb-operator/mariadb-operator#569]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

**Expected behaviour**

**Steps to reproduce the bug**

1. ...
2. ...
3. ...

**Debug information**
- Related object events:
```bash
kubectl get events --field-selector involvedObject.name=<mariadb-resource-name>
kubectl get events --field-selector involvedObject.name=<backup-resource-name>
kubectl get events --field-selector involvedObject.name=<restore-resource-name>
```
- `mariadb-operator` logs. Set the `--log-level` to `debug` if needed.

**Environment details**:
- Kubernetes version: v1.30.0
- Kubernetes distribution: k8
- mariadb-operator version: latest
- Install method: [helm, OLM, or static manifests]
- Install flavor: [minimal, recommended, or custom]

**Additional context**

**Comment by mmontes11** [comment]
Hey @cyford! Thanks for reporting.

This has been addresses in https://github.com/mariadb-operator/mariadb-operator/pull/566.

It will be released in `v0.0.28` shortly, stay tuned!
