### ISSUE TITLE
[Bug] Cannot Access MaxScale GUI Interface in Multi-Instance StatefulSet

### ISSUE THREAD

**Issue by luohaha3123** [mariadb-operator/mariadb-operator#576]
**Documentation**
- [ ] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
I am facing an issue while deploying MaxScale in a multi-instance setup. When I have multiple instances running, I am unable to access the MaxScale GUI interface. However, I can successfully access the GUI interface when deploying a single instance or when only one instance is running.

Upon investigating the issue, I found that when I try to access the GUI interface with multiple instances running, I receive a "401 Unauthorized" error. To gather more information, I inspected the browser console using the F12 developer tools.

**Expected behaviour**

**Environment details**:
- Kubernetes version: [1.17.2]
- mariadb-operator version: [0.0.27]
- Install method: [helm]
- Install flavor: [custom]

**Additional context**

**Comment by mmontes11** [comment]
Hey there @luohaha3123 ! Thanks for reporting

This should be solved by https://github.com/mariadb-operator/mariadb-operator/issues/563. We have plans to support it shortly.

Thanks!

**Comment by luohaha3123** [comment]
@mmontes11 Thank you for your response. Based on #563 , I have tried modifying the **ServiceAffinity** to **ClientIP** mode and found that it allows for normal access. However, I'm unsure if this approach would impact the load balancing capability of the Service.

**Comment by luohaha3123** [comment]
@mmontes11 Thanks!
