### ISSUE TITLE
[Bug]  caPath value not used when cert-manager is enabled

### ISSUE THREAD

**Issue by nlindblo** [mariadb-operator/mariadb-operator#614]
**Documentation**
- [ X] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

I am trying to configure the Helm values to use cert-manager. The CA that I am using (step-issuer) has an Intermediate issuer meaning that the ca.crt in the secret does not have the full chain trust and the validation fails. I have mounted my full chain ca.crt as an extraVolume and thought that I would be able to point the caPath to this file. However, the logic in the chart does not read this value when cert-manager is enabled and defaults to the path where the tls.key and tls.crt are stored. I am not sure if this is by the design, but it feels reasonable to be able to point to a different ca file when cert-manager is enabled as an option.
```
            - webhook
            {{- if .Values.webhook.cert.certManager.enabled }}
            - --ca-cert-path={{ .Values.webhook.cert.path }}/ca.crt
            {{- else }}
            - --ca-cert-path={{ .Values.webhook.cert.caPath }}/tls.crt
            {{- end }}
```
-->

**Expected behaviour**
caPath to be honoured in all circumstances 

**Steps to reproduce the bug**

1.  set certManager: true
2. specify a caPath for root certificate ca to be trusted

**Debug information**
- Related object events:
```
{"level":"info","ts":1715587943.4047732,"logger":"setup","msg":"Validating certs"}
{"level":"debug","ts":1715587943.405234,"logger":"setup","msg":"Error validating certificate","error":"Certificate is not valid for mariadb-operator-app-webhook.kube-utils.svc"}
```
- `mariadb-operator` logs. Set the `--log-level` to `debug` if needed.

**Environment details**:
- Kubernetes version: 1.29.3
- Kubernetes distribution:Vanilla
- mariadb-operator version: Helm 0.28.1
- Install method: ArgoCD
- Install flavor: recommended

**Additional context**

**Comment by nlindblo** [comment]
Awesome, how will this fix manifest itself, will there be a new Helm release available or how can I apply the caPath setting ?

Thanks for the quick turnaround

**Comment by mmontes11** [comment]
Hey @nlindblo ! Yes, we normally do a month release which includes a release of the helm chart.

If you want to start testing it now, you can clone the repo and apply the helm chart locally, the changes are already in `main`
https://github.com/mariadb-operator/mariadb-operator/tree/main/deploy/charts/mariadb-operator
