### ISSUE TITLE
`v0.0.29`

### ISSUE THREAD

**Issue by mmontes11** [mariadb-operator/mariadb-operator#637]
- [x] Change `v0.0.29-dev` to `v0.0.29` and run `make gen` in [release-v0.0.29](https://github.com/mariadb-operator/mariadb-operator/tree/release-v0.0.29) branch

### Examples
Add the following examples in `examples/`, `config/samples` and `mariadb-operator-helm`:
- [x] Updates: `ReplicastFirstPrimaryLast`
- [x] `my.cnf` configuration: 
   - [innodb_buffer_pool_size](https://mariadb.com/kb/en/innodb-buffer-pool/) in `myCnf`
   - user-provided `my.cnf` `ConfigMap` (not owned by `MariaDB`).
 - [x] Label `examples/manifests/config` with `k8s.mariadb.com/watch`
    
### Documentation
- [x] README.md: rolling updates, my.cnf configuration.
- [x] `Mariadb`
  - Rolling updates
  - my.cnf configuration
- [x] External resources: should be labeled with `k8s.mariadb.com/watch` in order to update.
- [ ] Release notes
- [ ] Update [MariaDB docs](https://mariadb.com/kb/en/kubernetes-operators-for-mariadb/)

 ### E2E tests
 - [x] Double check [`myCnf` and `myCnfConfigMapKeyRef` webhook mutability](https://github.com/mariadb-operator/mariadb-operator/pull/655)
- [x] Test rolling updates
- [x] Test my.cnf change
- [x] Test examples

## PRs

- https://github.com/mariadb-operator/mariadb-operator/pull/673

**Comment by mariadb-pieterhumphrey** [comment]
added a gh label for 0.0.29-release
