### ISSUE TITLE
[Feature] Management UI

### ISSUE THREAD

**Issue by Dan6erbond** [mariadb-operator/mariadb-operator#64]
**Is your feature request related to a problem? Please describe.**

Many operators out there, such as Zalando's Postgres Operator, Stackgres and MinIO have a UI to create and manage deployments. I like this for monitoring purposes, because it enables a better overview of the available options and deployments.

**Describe the solution you'd like**

Some kind of management UI, to create and view deployments, change any mutable options, restart deployments to apply those configurations, and anything else that makes sense to have in a operator UI. Additionally, it could integrate with OIDC or Kubernetes RBAC for authentication.

**Describe alternatives you've considered**

Well, using `kubectl` and the CRDs, but sometimes a UI is just simpler.

**Additional context**

I'd love to help out with this, if there's a vision for this project then collaborating with its creators would make sense. I have skills in both Go and React, so building a dashboard and management UI shouldn't be too hard. Would love to hear if this is on the roadmap, and how I can help!

**Comment by mmontes11** [comment]
Hey @Dan6erbond  ! This is defintely a feature we a feature we should support eventually, adding it to the long term roadmap. We have an ambitious [roadmap](https://github.com/mariadb-operator/mariadb-operator/blob/main/ROADMAP.md) ahead which contain features that can potentially be worth displayed in the management UI, like the high availability and replication. We can catch up in this issue and discuss which of them should be displayed in the UI once they are implemented.

Stay tuned for future releases! Thanks! 🙏🏻

**Comment by laurivosandi** [comment]
I would rather recommend spending workhours for something else:
* GitOps workflows imply declarative management of database instances anyway, so imperative commands to create or destroy database instances does not make sense
* For read-only dashboard rather implement decent metrics and expose them via Grafana

**Comment by mmontes11** [comment]
Hey there!

With the release of [v0.0.25](https://github.com/mariadb-operator/mariadb-operator/releases/tag/v0.0.25), we have supported MaxScale, with has a great user interface:
https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/MAXSCALE.md#maxscale-gui

Shall we close this in favor of MaxScale GUI?

**Comment by mmontes11** [comment]
Also worth mentioning that OpenShift does provide a UI to manage operators and CRDs, so for now I think we don't need a management UI. Thanks for reporting anyway!
