### ISSUE TITLE
Support for successfuljobshistorylimit and failedjobshistorylimit in backups.k8s.mariadb.com

### ISSUE THREAD

**Issue by Stenstromen** [mariadb-operator/mariadb-operator#641]
I have a mariadb backup (sql dump) that fires every evening, and this creates a k8s job as expected.

This creates a completed k8s job (pod) when completed successfully in the specified backup namespace.

I would like, as with other *cronjob.batch* to be able to specify a successfuljobshistorylimit and failedjobshistorylimit. So that I can decide if I want a successful jobs history or not. 

I've had a look through other github issues in this repo and I haven't found the question being asked before. I have also tried to apply a failedjobshistorylimit to a backups.k8s.mariadb.com yaml, but FluxCD says it is not available in the schema.

**Environment details**:
- Kubernetes version: 1.29.4
- Kubernetes distribution: k3s
- mariadb-operator version: 0.0.27
- Install method:helm
- Install flavor: recommended

**Comment by mmontes11** [comment]
Hey there @Stenstromen ! Thanks for bringing this up.

> I would like, as with other cronjob.batch to be able to specify a successfuljobshistorylimit and failedjobshistorylimit. So that I can decide if I want a successful jobs history or not.

I can confirm that this fields are not yet supported, but it would be great if we could support them in our scheduled `Backup` and `SqlJob` resources:
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#jobs-history-limits

Contributions welcome!

**Comment by mmontes11** [comment]
@mbezhanov has kindly contributed this via https://github.com/mariadb-operator/mariadb-operator/pull/721. Will be released in `v0.0.30`, stay tuned!
