### ISSUE TITLE
[Feature] modifying users?

### ISSUE THREAD

**Issue by pasztorl** [mariadb-operator/mariadb-operator#685]
If I create an User object the maxUserConnections become immutable. So If I want to adjust this setting I need to recreate the user. I think this is not so good in prod environment because when I delete the user the application can't connect to it, so it will be a downtime while the new user not created by the operator. So can you please consider to manage the users more dynamically?
Thanks!

**Comment by mmontes11** [comment]
Hey there!

Fair enough! We have significantly improved the SQL object reconciliation in the last release, managing the updates of the `User` password, we could extend the `ALTER USER` statement used for reconciliation and also update the max connections.

For making this usable, we also need to make the `maxConnections` mutable, as you pointed out.

Contributions welcome!

**Comment by AayushVinayDev** [comment]
Hi @mmontes11 @pasztorl can i contribute to this?

**Comment by mmontes11** [comment]
Thanks for your [PR](https://github.com/mariadb-operator/mariadb-operator/pull/723) @AayushVinayDev ! I've left some comments

**Comment by AayushVinayDev** [comment]
@mmontes11 Heyy!! Sorry about the delay, was busy with finals. I've made some changes as suggested, I'll commit them and write the tests when given the green signal. : )
