### ISSUE TITLE
[Feature]How to write the can embrace GitOps best practises by using this operator using ArgoCD

### ISSUE THREAD

**Issue by saibattula93** [mariadb-operator/mariadb-operator#697]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Environment details**:
- Kubernetes version: [Version number]
- Kubernetes distribution: [Vanilla, EKS, GKE, AKS, Rancher, OpenShift, k3s, KIND...]
- mariadb-operator version: [Version number]
- Install method: [helm, OLM, or static manifests]
- Install flavor: [minimal, recommended, or custom]

**Additional context**

**Comment by sennerholm** [comment]
I'm running the operator with ArgoCD, but I really don't know what kind of info you want.

**Comment by saibattula93** [comment]
After running the mariadb operator using Helm chart, How to creat a Mariadb-instance, database, user and grants and so on, like you see the mariadb-operator github we follow the quick start section in the README.md file and I want the information about how to perform that all operations in the ArgoCD??

**Comment by mmontes11** [comment]
This has been discussed here:
- https://mariadb-community.slack.com/archives/C06AWJBAC1H/p1719407979965279

After talking with @sennerholm, we concluded that an ArgoCD example will help. Something similar to our current [flux example](https://github.com/mariadb-operator/mariadb-operator/tree/main/examples/flux).

**Comment by saibattula93** [comment]
Yes, I have solved the issue, thanks to sennerholm.

**Comment by ifalex** [comment]
Unfortunately the slack channel was archived and the documentation was updated @saibattula93, how did you solved your issues? Currently hitting this bug https://github.com/mariadb-operator/mariadb-operator/issues/1123 when trying this approach.
