### ISSUE TITLE
[Bug] Faulty indentation in the `webhook-certificate.yaml` helm template

### ISSUE THREAD

**Issue by kettil** [mariadb-operator/mariadb-operator#700]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

The indentation of [secretAnnotations](https://github.com/mariadb-operator/mariadb-operator/blob/8f752f59fa4cea17b293297c376c935023cd4c3e/deploy/charts/mariadb-operator/templates/webhook-certificate.yaml#L47) is faulty. 

The object is only indented by 4 spaces, but should be indented by 6 spaces.

```diff
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "mariadb-operator.fullname" . }}-webhook-cert
  # ...
spec:
  # ...

  secretTemplate:
    {{- with .Values.webhook.cert.secretLabels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.webhook.cert.secretAnnotations }}
    annotations:
-     {{- toYaml . | nindent 4 }}
+     {{- toYaml . | nindent 6 }}
    {{- end }}

  # ...
```

**Comment by mmontes11** [comment]
Thanks for bringing this up! 

We definetly need to add more test cases for helm, and not just render the default values in the CI:
https://github.com/mariadb-operator/mariadb-operator/blob/main/.github/workflows/helm.yml

Would you mind raising a PR with this?

**Comment by mmontes11** [comment]
Just seen the new PR! Looking into it! 👀
