### ISSUE TITLE
[Bug] adding sidecarContainers with galera is not working

### ISSUE THREAD

**Issue by sujitkagarwal** [mariadb-operator/mariadb-operator#705]
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  sidecarContainers:
    - image: busybox:1.36
      args:
        - sleep
        - infinity

  storage:
    size: 1Gi

  replicas: 3
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
    generate: false

  galera:
    enabled: true
    config:
      reuseStorageVolume: true

**Documentation**
- [ ] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

**Expected behaviour**

**Steps to reproduce the bug**

1. ...
2. ...
3. ...

**Debug information**
- Related object events:
```bash
kubectl get events --field-selector involvedObject.name=<mariadb-resource-name>
kubectl get events --field-selector involvedObject.name=<backup-resource-name>
kubectl get events --field-selector involvedObject.name=<restore-resource-name>
```
- `mariadb-operator` logs. Set the `--log-level` to `debug` if needed.

**Environment details**:
- Kubernetes version: [Version number]
- Kubernetes distribution: [Vanilla, EKS, GKE, AKS, Rancher, OpenShift, k3s, KIND...]
- mariadb-operator version: [Version number]
- Install method: [helm, OLM, or static manifests]
- Install flavor: [minimal, recommended, or custom]

**Additional context**

**Comment by mmontes11** [comment]
Please, fill the issue template and provide a description of your issue. In this case, a definition of the reconciled `Pods`.
