### ISSUE TITLE
[Feature] Possibility to define the local storage for backup job

### ISSUE THREAD

**Issue by bennyvar77** [mariadb-operator/mariadb-operator#786]
**Is your feature request related to a problem? Please describe.**
I am using minio to store the backups. The backups are however generated temporarily on the local storage. This storage is limited to the space currently available on the node. On creating a backup for big DBs, the job fails because the storage on the node is not enough

**Describe the solution you'd like**
It would be good to define the temporary storage in addition to "storage". This would allow the usage of Azure Files.

**Describe alternatives you've considered**
Increasing the storage on the node. Very cost intensive!

**Environment details**:
- Kubernetes version: v1.29.2
- Kubernetes distribution: AKS
- mariadb-operator version: v0.0.29
- Install method: 
- Install flavor: 

**Additional context**

**Comment by ebuzzz** [comment]
Allowing the spec to overwrite the existing emptyDir volume mount for the `backup` volume would also be sufficient.

**Comment by mmontes11** [comment]
This has been addressed by https://github.com/mariadb-operator/mariadb-operator/pull/946. Take a look at the PR body to see how to use this new feature and stay tuned for the next release! 🚀
