### ISSUE TITLE
[Bug] Openshift - Database import doesn't work when the database is created by yaml. 

### ISSUE THREAD

**Issue by pKary86** [mariadb-operator/mariadb-operator#804]
**Documentation**
- [x ] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

In mariadb-operator. After creating a mariadb. 
Inside the mariadb I can execute create database test1; then mysql -u root -p test1 < dumpfromold.sql
This import works perfectly. 

If the database is created with a yaml file with the create Database function in the gui, eg test2. Then executing: mysql -u root -p test2 < dumpfromold.sql hangs halfway completely. 

Comparing the 2 databases all variables are the same. 
Executing eg SHOW ENGINE INNODB STATUS\G gives a result:
---TRANSACTION 2367, ACTIVE 626 sec
mysql tables in use 1, locked 1
1 lock struct(s), heap size 1128, 0 row lock(s), undo log entries 155
MariaDB thread id 2491, OS thread handle 139631803426368, query id 17556 localhost root Waiting for certification
 INSERT INTO `cg.....
 ....---TRANSACTION (0x7efe5d91ab80), not started 

**Expected behaviour**

Importing the dump should work with databases created with the Create Database / yaml. 

**Steps to reproduce the bug**

1. Create the dump from a database.
2. Create a database inside the mariadb with create database command.
3. Create a database with the gui function of the operator. 
4. Import into the command created database.
5. Import into the yaml created database.

Operator is

ClusterServiceVersion
CSV
[mariadb-operator.v0.29.0]

**Comment by mmontes11** [comment]
Hey there @pKary86 ! 

The whole point of this operator is not performing manual commands inside the container. Instead we offer CRDs to deal with, backup, restore and create database:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/backup.yaml
- https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/restore.yaml
- https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/database.yaml

I encourage you to give it a try! Cheers!

**Comment by pKary86** [comment]
Yes. We have an old helm rolled out mariadb-galera cluster. That is not managed by an operator. 
So I can't call 
spec:
  mariaDbRef:
    name: mariadb
  on it bc there is no mariadb resource for it.
