### ISSUE TITLE
[Feature] add option for service type

### ISSUE THREAD

**Issue by obeyler** [mariadb-operator/mariadb-operator#877]
For some test case, the service exposing mariadb must be set as NodePort instead of ClusterIP
Now the operator doesn't allow this option

**Comment by ambled** [comment]
+1

**Comment by mmontes11** [comment]
Hey there! Thanks for bringing this up.

You are able to specify the service type by setting `type = <service-type>`, as shown in the following example:
https://github.com/mariadb-operator/mariadb-operator/blob/cf116921ee5fb27a1e43a8f5bb2b8170a4e332b4/examples/manifests/mariadb_galera.yaml#L19

It is also documented in the API docs:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/API_REFERENCE.md#servicetemplate

I will be closing this one, feel free to reopen and let me know if this covers your use case.

Thanks!

**Comment by mmontes11** [comment]
Hey @ambled ! 

We currently don't support static `nodePorts`. Alternatively, you can use something like [metallb](https://metallb.universe.tf/), use a `LoadBalancer` instead, and specify a static IP for your `Services`:
https://github.com/mariadb-operator/mariadb-operator/blob/d3e6784cd580b32a5df99bb05bef95e0b1b40774/examples/manifests/mariadb_galera.yaml#L22

Would that cover your use case? If it doesn't, please file another issue for the static `nodePort` support,

**Comment by ambled** [comment]
My environment doesn't support dynamic ip, so metallb doesn't fill my edge case, however I'm just exploring the options vs something that needs deployment imminently.

Thank you!
