### ISSUE TITLE
[Bug] Unify versioning. Operator image, Helm chart and CRDs Helm chart with the same version.

### ISSUE THREAD

**Issue by jurlwin** [mariadb-operator/mariadb-operator#891]
**Documentation**
- [ X] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

From the upgrade guide (and trying it) name of crd release 0.0.32 vs 0.32.0 in operator -- wouldn't these be better to both be 0.32.0 (or for next version?)
... 
helm install $CRDS_RELEASE_NAME -n $CRDS_RELEASE_NAMESPACE mariadb-operator/mariadb-operator-crds --version 0.0.32 

helm repo update mariadb-operator
helm upgrade --install mariadb-operator mariadb-operator/mariadb-operator --version 0.32.0 
``` 
**Expected behaviour**

Ability to track one version number in scripts for both CRDs and Operator


**Steps to reproduce the bug**

helm install --version 0.0.32 for the operator fails.  Needs 0.32.0.  I would think the operator should follow version numbers the same way

**Comment by mmontes11** [comment]
Thanks for asking!

`mariadb-operator-crds` helm chart has the same versioning as the operator, which is `v0.0.32` now. We are using patch versions to indicate that we are in early stage, but we will soon launch our first minor version `v0.1.0`

`mariadb-operator` helm chart  it is considered more mature than the operator, and therefore we are using minor versions already. Also, the lifecycle of the `mariadb-operator` helm chart is not coupled to the operator, so it doesn't necesarily need to be the same.

I know it might be a bit confusing at the moment, but hopefully we will be able to sort this out once the release the first minor version of the operator: `v0.1.0`.

Sorry for the confusion!

**Comment by jurlwin** [comment]
if you think i'm confused now -- I can't wait until they don't need to be in sync ;)

Thanks for the explanation, but won't that drive some confusion for users later?  Install new, i get 0.1.0 of this and 0.2.0 of that, but they both have the mariadb-operator as the core name.  From the outside in - I see the **technical reason**, but the human thing would be to keep them aligned even if there are no changes between .32 and .33 for example.

**Comment by mmontes11** [comment]
I see the **human reason** to keep them in sync as well, so le't keep this open so people can leave their input. We still have some time to decide until we release the first minor version, where we could introduce this change in versioning.

I can give you an example which follows the same **technical reasoning**:
- Traefik: https://github.com/traefik/traefik/releases/tag/v3.1.4
- Traefik Helm Chart: https://github.com/traefik/traefik-helm-chart/releases/tag/v32.0.0

**Comment by mmontes11** [comment]
As an idea to sync the versions avoid confussion, we could use `0.33.0`  as the next version of both the `mariadb-operator` image, `mariadb-operator` Helm chart and `mariadb-operator-crds` Helm chart. Is what you would expect @jurlwin ?

**Comment by jurlwin** [comment]
Yes, I agree -- use 0.33.0 for both sounds reasonble for next release.  I think the Traefik example does demonstrate difference in versioning... but -- I would submit that the CRDs are more tied to the operator functioning than the helm chart is to the functions of Traefik.   I realize you are working around some - well - tough design decisions with this.   I don't know the best solution .. out of curiosity -- can the mariadb operator itself upgrade the CRDs?  I realize in the past, I had to save some info, replace the name to the k8s.mariadb.com and that was a bigger change...  Sorry I don't have a better suggestion but I feel that syncing the version numbers will at least make it more "discoverable" for users... (maybe not the best term, but I think palatable, usable, understandable may fit.  SO thank you for considering...

and thanks for the good work.  I've been using this for my education on a small cluster of Pis.  fun!

**Comment by jurlwin** [comment]
I can’t wait!
