### ISSUE TITLE
HA: openark orchestrator

### ISSUE THREAD

**Issue by MAXxATTAXx** [mariadb-operator/mariadb-operator#9]
Provide HA by adding support of multiple topologies by using https://github.com/openark/orchestrator

**Comment by mmontes11** [comment]
We are considering the official MariaDB Galera to support HA:
- https://github.com/mmontes11/mariadb-operator/issues/4

What advantages does [openark/orchestrator](https://github.com/openark/orchestrator) have over Galera?
