### ISSUE TITLE
[Bug] Sidecar deployment of monitoring does not work anymore after upgrading to v0.34.0

### ISSUE THREAD

**Issue by bennyvar77** [mariadb-operator/mariadb-operator#930]
Not able to deploy sidecare container with operator version v0.34.0 anymore

**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

We have a semisync deployment and are not using galera

We have the following Sidecar for monitoring the db with percona

<code>
  sidecarContainers:
      - image: registry.cute.dlh.de/percona/pmm-client:2.41.1
        imagePullPolicy: IfNotPresent
        env:
          - name: PMM_ADMIN_CUSTOM_PARAMS
            valueFrom:
              secretKeyRef:
                name: matomo-db-pmm
                key: PMM_ADMIN_CUSTOM_PARAMS
          - name: PMM_AGENT_SERVER_ADDRESS
            valueFrom:
              secretKeyRef:
                name: matomo-db-pmm
                key: PMM_SERVER_ADDRESS
          - name: PMM_AGENT_SERVER_USERNAME
            value: api_key
          - name: PMM_AGENT_SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: matomo-db-pmm
                key: PMM_SERVER_API_KEY
          - name: PMM_SERVER
            valueFrom:
              secretKeyRef:
                name: matomo-db-pmm
                key: PMM_SERVER_ADDRESS
          - name: PMM_USER
            value: api_key
          - name: PMM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: matomo-db-pmm
                key: PMM_SERVER_API_KEY
          - name: CLUSTER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app.kubernetes.io/instance']
          - name: DB_CLUSTER
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app.kubernetes.io/name']
          - name: DB_USER
            value: pmm
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: matomo-db
                key: pmm-password
          - name: DB_HOST
            value: localhost
          - name: DB_PORT
            value: '3306'
          - name: CLIENT_PORT_LISTEN
            value: '7777'
          - name: CLIENT_PORT_MIN
            value: '30100'
          - name: CLIENT_PORT_MAX
            value: '30105'
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPASE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: PMM_AGENT_LISTEN_PORT
            value: '7777'
          - name: PMM_AGENT_PORTS_MIN
            value: '30100'
          - name: PMM_AGENT_PORTS_MAX
            value: '30105'
          - name: PMM_AGENT_CONFIG_FILE
            value: /usr/local/percona/pmm2/config/pmm-agent.yaml
          - name: PMM_AGENT_SERVER_INSECURE_TLS
            value: '1'
          - name: PMM_AGENT_LISTEN_ADDRESS
            value: 0.0.0.0
          - name: PMM_AGENT_SETUP_NODE_NAME
            value: $(POD_NAMESPASE)--$(POD_NAME)
          - name: PMM_AGENT_SETUP_METRICS_MODE
            value: push
          - name: PMM_AGENT_SETUP
            value: '1'
          - name: PMM_AGENT_SETUP_FORCE
            value: '1'
          - name: PMM_AGENT_SETUP_NODE_TYPE
            value: container
          - name: PMM_AGENT_SETUP_REGION
            value: azure
          - name: PMM_AGENT_SETUP_AZ
            value: ams
          - name: PMM_AGENT_PRERUN_SCRIPT
            value: >-
              set -o errexit;
              pmm_args=();
              read -ra PMM_ADMIN_CUSTOM_PARAMS_ARRAY <<<"$PMM_ADMIN_CUSTOM_PARAMS";
              pmm_args+=("${PMM_ADMIN_CUSTOM_PARAMS_ARRAY[@]}");
              pmm-admin status --wait=10s;
              pmm-admin add mysql --service-name="$PMM_AGENT_SETUP_NODE_NAME" --skip-connection-check --query-source=perfschema --metrics-mode=push --username="$DB_USER" --password="$DB_PASSWORD" --cluster="$CLUSTER_NAME" --replication-set="$CLUSTER_NAME" "${pmm_args[@]}";
              pmm-admin annotate --service-name="$PMM_AGENT_SETUP_NODE_NAME" 'Service restarted'
          - name: PMM_AGENT_SIDECAR
            value: 'true'
          - name: PMM_AGENT_SIDECAR_SLEEP
            value: '5'
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /local/Status
            port: 7777
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
          - name: storage
            mountPath: /var/lib/mysql
</code>
One problem seems to be that the env part of the definition is no longer accepted by the api/crd.

Another one appears to be that the sidecare can no longer mount "mountPath: /var/lib/mysql". It produced the following error
invalid: spec.containers[2].volumeMounts[5].mountPath: Invalid value: "/var/lib/mysql": must be unique 
Is this path mounted by default?

**Expected behaviour**
Deployment of a custom sidecar container should would as it was working before

**Steps to reproduce the bug**

1. Deploy a semisync maria db 
2. Add the above mentioned sidecar container

**Environment details**:
- Kubernetes version: [v1.29.7]
- Kubernetes distribution: [AKS]
- mariadb-operator version: [0.34.0]
- Galera data-plane version (init and agent): [nil]
- Install method: [static manifests]

**Comment by mmontes11** [comment]
Hey there @bennyvar77  ! Thanks for reporting this.

We've recently made a [huge refactor to our CRDs to reduce its size by ~81%](https://github.com/mariadb-operator/mariadb-operator/pull/869).  Unfortunately, it seems like we left behind some fields, like the `env` field in the `sidecarContainers`.

Supporting them should be doadble, we need to extend our custom `Container` type:
https://github.com/mariadb-operator/mariadb-operator/blob/fec9288ab85e622507c6a0d12d45595c61b048f3/api/v1alpha1/base_types.go#L145

We have plans to release a minor version fixing the problems derived from the CRD refactor. PRs more than welcome!

> Another one appears to be that the sidecare can no longer mount "mountPath: /var/lib/mysql". It produced the following error
invalid: spec.containers[2].volumeMounts[5].mountPath: Invalid value: "/var/lib/mysql": must be unique
Is this path mounted by default?

Regarding this, yes, `SidecarContainers` have the same mounts as the main `MariaDB` container, so you don't need to provide an extra `volumeMount` to access `/var/lib/mysql`, it is the default behaviour.

Sorry for the inconvenience!

**Comment by hedgieinsocks** [comment]
I had to declare custom env in mariadb spec to overcome this issue. They get projected to all containers, that is not ideal. But at least they become available.
