### ISSUE TITLE
[Bug] replication on custom ports is not supported

### ISSUE THREAD

**Issue by onesolpark** [mariadb-operator/mariadb-operator#948]
**Documentation**
- [X] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

**Expected behaviour**

**Steps to reproduce the bug**

1. set spec.port to 4306
2. set custom my.cnf and set port to 4306
3. set replication to true

**Debug information**
- Related object events:
mariadb slave (statefulset 1 log)
```2024-10-18  2:21:47 15 [Note] Master 'mariadb-operator': Slave SQL thread exiting, replication stopped in log 'FIRST' at position 4; GTID position '', master: mariadb-operator-0.mariadb-operator-internal:3306```
- `mariadb-operator` logs. Set the `--log-level` to `debug` if needed.

**Environment details**:
- Kubernetes version: 1.28.7
- Kubernetes distribution: Vanilla
- mariadb-operator version: 0.30.0
- Install method: helm

**Additional context**

**Comment by mmontes11** [comment]
Thanks for reporting @onesolpark ! I can confirm I've managed to reproduce the problem using this resource:

```yaml
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-repl
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  storage:
    size: 1Gi

  replicas: 3

  replication:
    enabled: true

  port: 4306

  metrics:
    enabled: true
```

Which resulted in the following errors in the `Pods`:
```bash
Version: '11.4.3-MariaDB-ubu2404-log'  socket: '/run/mysqld/mysqld.sock'  port: 4306  mariadb.org binary d
istribution
2024-10-21 11:01:17 8 [Note] Deleted Master_info file '/var/lib/mysql/master.info'.
2024-10-21 11:01:17 8 [Note] Deleted Master_info file '/var/lib/mysql/relay-log.info'.
2024-10-21 11:01:17 8 [Note] Semi-sync replication enabled on the master.
2024-10-21 11:01:17 0 [Note] Starting ack receiver thread
2024-10-21 11:01:17 8 [Note] Deleted Master_info file '/var/lib/mysql/master.info'.
2024-10-21 11:01:17 8 [Note] Deleted Master_info file '/var/lib/mysql/relay-log.info'.
2024-10-21 11:01:27 8 [Warning] Timeout waiting for reply of binlog (file: mariadb-repl-bin.000002, pos: 1
121), semi-sync up to file , position 0.
2024-10-21 11:01:27 8 [Note] Semi-sync replication switched OFF.
```
The `Pods` and the `Services` are exposing the right port`:
```bash
❯ k get pod mariadb-repl-0 -o jsonpath="{.spec.containers[0].ports}" | jq
[
  {
    "containerPort": 4306,
    "name": "mariadb",
    "protocol": "TCP"
  }
]

❯ k get svc mariadb-repl-internal -o jsonpath="{.spec.ports} | jq"
[{"name":"mariadb","port":4306,"protocol":"TCP","targetPort":4306}] | jq
```

**Comment by onesolpark** [comment]
https://github.com/mariadb-operator/mariadb-operator/blob/5c4e09f1f7523a5a7a7a3a7887122f601ed6a857/pkg/sql/sql.go#L510-L530

seems like port is not specified so it tries to sync/replicate through default port

**Comment by mmontes11** [comment]
@onesolpark great catch, you are absolutely right. We need to add the `MASTER_PORT` option to the `CHANGE MASTER` statement:
- https://mariadb.com/kb/en/change-master-to/

Would you like to raise a PR with this? 🙏🏻

**Comment by onesolpark** [comment]
yeah I'll work on this.
