### ISSUE TITLE
[Bug] mariadbd: Please consult the Knowledge Base to find out how to run mysqld as root!

### ISSUE THREAD

**Issue by wirehack7** [mariadb-operator/mariadb-operator#973]
**Documentation**
- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
When the recovery pods are deployed by the operator they are running in an issue:

```
mariadbd: Please consult the Knowledge Base to find out how to run mysqld as root!
2024-10-28  7:46:06 0 [ERROR] Aborting
```
In specs of mariaDB deployment is this setting:

```
securityContext:
    allowPrivilegeEscalation: false
podSecurityContext:
    runAsUser: 0
```

**Expected behaviour**
Recovery pods shhould run properly

**Steps to reproduce the bug**

1. Downtime of mariadb
2. operator deploys recovery jobs

**Environment details**:
- Kubernetes version: 1.29
- Kubernetes distribution: EKS
- mariadb-operator version: 0.34.0
- Galera data-plane version (init and agent): 0.34.0
- Install method: HELM/ArgoCD

**Comment by taxilian** [comment]
... some details on this would be helpful for cases where others hit the same issue. I am having this problem and I can't figure out how to fix it.
